/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../../../..";

/**
 * @example
 *     {
 *         model: {
 *             lineItems: [{
 *                     remoteId: "121222",
 *                     description: "Pickleball paddles",
 *                     unitPrice: 25,
 *                     quantity: 10,
 *                     trackingCategory: "f1214c24-2702-4617-b74b-3ddecfc0d384",
 *                     trackingCategories: [],
 *                     exchangeRate: "2.9",
 *                     company: "595c8f97-2ac4-45b7-b000-41bdf43240b5"
 *                 }]
 *         }
 *     }
 */
export interface PurchaseOrderEndpointRequest {
    /**
     * Whether to include debug fields (such as log file links) in the response.
     */
    isDebugMode?: boolean;
    /**
     * Whether or not third-party updates should be run asynchronously.
     */
    runAsync?: boolean;
    model: Merge.accounting.PurchaseOrderRequest;
}
