// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const CompanyInfoRetrieveRequestExpandItem: core.serialization.Schema<
    serializers.accounting.CompanyInfoRetrieveRequestExpandItem.Raw,
    Merge.accounting.CompanyInfoRetrieveRequestExpandItem
> = core.serialization.enum_(["addresses", "phone_numbers"]);

export declare namespace CompanyInfoRetrieveRequestExpandItem {
    export type Raw = "addresses" | "phone_numbers";
}
