/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The job being applied for.
 */
export type ApplicationJob = string | Merge.ats.Job;
