// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

/**
 * The application's reason for rejection.
 */
export type ApplicationRequestRejectReason = string | Merge.ats.RejectReason;
