/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * # The Attachment Object
 *
 * ### Description
 *
 * The `Attachment` object is used to represent a file attached to a candidate.
 *
 * ### Usage Example
 *
 * Fetch from the `LIST Attachments` endpoint and view attachments accessible by a company.
 */
export interface Attachment {
    id?: string;
    /** The third-party API ID of the matching object. */
    remoteId?: string;
    /** The attachment's name. */
    fileName?: string;
    /** The attachment's url. */
    fileUrl?: string;
    /** */
    candidate?: string;
    /**
     * The attachment's type.
     *
     * - `RESUME` - RESUME
     * - `COVER_LETTER` - COVER_LETTER
     * - `OFFER_LETTER` - OFFER_LETTER
     * - `OTHER` - OTHER
     */
    attachmentType?: Merge.ats.AttachmentAttachmentType;
    remoteWasDeleted?: boolean;
    createdAt?: Date;
    /** This is the datetime that this object was last updated by Merge */
    modifiedAt?: Date;
    fieldMappings?: Record<string, unknown>;
    remoteData?: Merge.ats.RemoteData[];
}
