// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

/**
 * The type of email address.
 *
 * * `PERSONAL` - PERSONAL
 * * `WORK` - WORK
 * * `OTHER` - OTHER
 */
export type EmailAddressEmailAddressType = Merge.ats.EmailAddressTypeEnum | string;
