/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListTrackingCategoriesRequestStatus = "" | "ACTIVE" | "ARCHIVED";
export const ListTrackingCategoriesRequestStatus = {
    Empty: "",
    Active: "ACTIVE",
    Archived: "ARCHIVED",
} as const;
