/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RetrieveSalesOrdersRequestExpand =
    | "company"
    | "company,payment_term"
    | "company,payment_term,shipping_address"
    | "company,shipping_address"
    | "customer"
    | "customer,company"
    | "customer,company,payment_term"
    | "customer,company,payment_term,shipping_address"
    | "customer,company,shipping_address"
    | "customer,payment_term"
    | "customer,payment_term,shipping_address"
    | "customer,shipping_address"
    | "lines"
    | "lines,company"
    | "lines,company,payment_term"
    | "lines,company,payment_term,shipping_address"
    | "lines,company,shipping_address"
    | "lines,customer"
    | "lines,customer,company"
    | "lines,customer,company,payment_term"
    | "lines,customer,company,payment_term,shipping_address"
    | "lines,customer,company,shipping_address"
    | "lines,customer,payment_term"
    | "lines,customer,payment_term,shipping_address"
    | "lines,customer,shipping_address"
    | "lines,payment_term"
    | "lines,payment_term,shipping_address"
    | "lines,shipping_address"
    | "lines,tracking_categories"
    | "lines,tracking_categories,company"
    | "lines,tracking_categories,company,payment_term"
    | "lines,tracking_categories,company,payment_term,shipping_address"
    | "lines,tracking_categories,company,shipping_address"
    | "lines,tracking_categories,customer"
    | "lines,tracking_categories,customer,company"
    | "lines,tracking_categories,customer,company,payment_term"
    | "lines,tracking_categories,customer,company,payment_term,shipping_address"
    | "lines,tracking_categories,customer,company,shipping_address"
    | "lines,tracking_categories,customer,payment_term"
    | "lines,tracking_categories,customer,payment_term,shipping_address"
    | "lines,tracking_categories,customer,shipping_address"
    | "lines,tracking_categories,payment_term"
    | "lines,tracking_categories,payment_term,shipping_address"
    | "lines,tracking_categories,shipping_address"
    | "payment_term"
    | "payment_term,shipping_address"
    | "shipping_address"
    | "tracking_categories"
    | "tracking_categories,company"
    | "tracking_categories,company,payment_term"
    | "tracking_categories,company,payment_term,shipping_address"
    | "tracking_categories,company,shipping_address"
    | "tracking_categories,customer"
    | "tracking_categories,customer,company"
    | "tracking_categories,customer,company,payment_term"
    | "tracking_categories,customer,company,payment_term,shipping_address"
    | "tracking_categories,customer,company,shipping_address"
    | "tracking_categories,customer,payment_term"
    | "tracking_categories,customer,payment_term,shipping_address"
    | "tracking_categories,customer,shipping_address"
    | "tracking_categories,payment_term"
    | "tracking_categories,payment_term,shipping_address"
    | "tracking_categories,shipping_address";
export const RetrieveSalesOrdersRequestExpand = {
    Company: "company",
    CompanyPaymentTerm: "company,payment_term",
    CompanyPaymentTermShippingAddress: "company,payment_term,shipping_address",
    CompanyShippingAddress: "company,shipping_address",
    Customer: "customer",
    CustomerCompany: "customer,company",
    CustomerCompanyPaymentTerm: "customer,company,payment_term",
    CustomerCompanyPaymentTermShippingAddress: "customer,company,payment_term,shipping_address",
    CustomerCompanyShippingAddress: "customer,company,shipping_address",
    CustomerPaymentTerm: "customer,payment_term",
    CustomerPaymentTermShippingAddress: "customer,payment_term,shipping_address",
    CustomerShippingAddress: "customer,shipping_address",
    Lines: "lines",
    LinesCompany: "lines,company",
    LinesCompanyPaymentTerm: "lines,company,payment_term",
    LinesCompanyPaymentTermShippingAddress: "lines,company,payment_term,shipping_address",
    LinesCompanyShippingAddress: "lines,company,shipping_address",
    LinesCustomer: "lines,customer",
    LinesCustomerCompany: "lines,customer,company",
    LinesCustomerCompanyPaymentTerm: "lines,customer,company,payment_term",
    LinesCustomerCompanyPaymentTermShippingAddress: "lines,customer,company,payment_term,shipping_address",
    LinesCustomerCompanyShippingAddress: "lines,customer,company,shipping_address",
    LinesCustomerPaymentTerm: "lines,customer,payment_term",
    LinesCustomerPaymentTermShippingAddress: "lines,customer,payment_term,shipping_address",
    LinesCustomerShippingAddress: "lines,customer,shipping_address",
    LinesPaymentTerm: "lines,payment_term",
    LinesPaymentTermShippingAddress: "lines,payment_term,shipping_address",
    LinesShippingAddress: "lines,shipping_address",
    LinesTrackingCategories: "lines,tracking_categories",
    LinesTrackingCategoriesCompany: "lines,tracking_categories,company",
    LinesTrackingCategoriesCompanyPaymentTerm: "lines,tracking_categories,company,payment_term",
    LinesTrackingCategoriesCompanyPaymentTermShippingAddress:
        "lines,tracking_categories,company,payment_term,shipping_address",
    LinesTrackingCategoriesCompanyShippingAddress: "lines,tracking_categories,company,shipping_address",
    LinesTrackingCategoriesCustomer: "lines,tracking_categories,customer",
    LinesTrackingCategoriesCustomerCompany: "lines,tracking_categories,customer,company",
    LinesTrackingCategoriesCustomerCompanyPaymentTerm: "lines,tracking_categories,customer,company,payment_term",
    LinesTrackingCategoriesCustomerCompanyPaymentTermShippingAddress:
        "lines,tracking_categories,customer,company,payment_term,shipping_address",
    LinesTrackingCategoriesCustomerCompanyShippingAddress:
        "lines,tracking_categories,customer,company,shipping_address",
    LinesTrackingCategoriesCustomerPaymentTerm: "lines,tracking_categories,customer,payment_term",
    LinesTrackingCategoriesCustomerPaymentTermShippingAddress:
        "lines,tracking_categories,customer,payment_term,shipping_address",
    LinesTrackingCategoriesCustomerShippingAddress: "lines,tracking_categories,customer,shipping_address",
    LinesTrackingCategoriesPaymentTerm: "lines,tracking_categories,payment_term",
    LinesTrackingCategoriesPaymentTermShippingAddress: "lines,tracking_categories,payment_term,shipping_address",
    LinesTrackingCategoriesShippingAddress: "lines,tracking_categories,shipping_address",
    PaymentTerm: "payment_term",
    PaymentTermShippingAddress: "payment_term,shipping_address",
    ShippingAddress: "shipping_address",
    TrackingCategories: "tracking_categories",
    TrackingCategoriesCompany: "tracking_categories,company",
    TrackingCategoriesCompanyPaymentTerm: "tracking_categories,company,payment_term",
    TrackingCategoriesCompanyPaymentTermShippingAddress: "tracking_categories,company,payment_term,shipping_address",
    TrackingCategoriesCompanyShippingAddress: "tracking_categories,company,shipping_address",
    TrackingCategoriesCustomer: "tracking_categories,customer",
    TrackingCategoriesCustomerCompany: "tracking_categories,customer,company",
    TrackingCategoriesCustomerCompanyPaymentTerm: "tracking_categories,customer,company,payment_term",
    TrackingCategoriesCustomerCompanyPaymentTermShippingAddress:
        "tracking_categories,customer,company,payment_term,shipping_address",
    TrackingCategoriesCustomerCompanyShippingAddress: "tracking_categories,customer,company,shipping_address",
    TrackingCategoriesCustomerPaymentTerm: "tracking_categories,customer,payment_term",
    TrackingCategoriesCustomerPaymentTermShippingAddress: "tracking_categories,customer,payment_term,shipping_address",
    TrackingCategoriesCustomerShippingAddress: "tracking_categories,customer,shipping_address",
    TrackingCategoriesPaymentTerm: "tracking_categories,payment_term",
    TrackingCategoriesPaymentTermShippingAddress: "tracking_categories,payment_term,shipping_address",
    TrackingCategoriesShippingAddress: "tracking_categories,shipping_address",
} as const;
