/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Merge from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const UpdateApplicationStageRequest: core.serialization.Schema<
    serializers.ats.UpdateApplicationStageRequest.Raw,
    Omit<Merge.ats.UpdateApplicationStageRequest, "isDebugMode" | "runAsync">
> = core.serialization.object({
    jobInterviewStage: core.serialization.property(
        "job_interview_stage",
        core.serialization.string().optionalNullable(),
    ),
    remoteUserId: core.serialization.property("remote_user_id", core.serialization.string().optional()),
});

export declare namespace UpdateApplicationStageRequest {
    export interface Raw {
        job_interview_stage?: (string | null) | null;
        remote_user_id?: string | null;
    }
}
