/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { Attachment } from "./Attachment";

export const ArticleAttachmentsItem: core.serialization.Schema<
    serializers.knowledgebase.ArticleAttachmentsItem.Raw,
    Merge.knowledgebase.ArticleAttachmentsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Attachment]);

export declare namespace ArticleAttachmentsItem {
    export type Raw = string | Attachment.Raw;
}
