// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const ExternalTargetFieldApi: core.serialization.ObjectSchema<
    serializers.knowledgebase.ExternalTargetFieldApi.Raw,
    Merge.knowledgebase.ExternalTargetFieldApi
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    isMapped: core.serialization.property("is_mapped", core.serialization.string().optional()),
});

export declare namespace ExternalTargetFieldApi {
    export interface Raw {
        name?: string | null;
        description?: string | null;
        is_mapped?: string | null;
    }
}
