/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { IssueStatusEnum } from "./IssueStatusEnum";

export const IssueStatus: core.serialization.Schema<
    serializers.knowledgebase.IssueStatus.Raw,
    Merge.knowledgebase.IssueStatus
> = core.serialization.undiscriminatedUnion([IssueStatusEnum, core.serialization.string()]);

export declare namespace IssueStatus {
    export type Raw = IssueStatusEnum.Raw | string;
}
