/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";

export const RolesEnum: core.serialization.Schema<
    serializers.knowledgebase.RolesEnum.Raw,
    Merge.knowledgebase.RolesEnum
> = core.serialization.enum_(["READ", "WRITE", "OWNER"]);

export declare namespace RolesEnum {
    export type Raw = "READ" | "WRITE" | "OWNER";
}
