// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient";
import { normalizeClientOptions } from "../../../../../../BaseClient";
import * as core from "../../../../../../core";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers";
import * as environments from "../../../../../../environments";
import * as errors from "../../../../../../errors/index";
import * as serializers from "../../../../../../serialization/index";
import type * as Merge from "../../../../../index";

export declare namespace TimeOffClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TimeOffClient {
    protected readonly _options: TimeOffClient.Options;

    constructor(options: TimeOffClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Returns a list of `TimeOff` objects.
     *
     * @param {Merge.hris.TimeOffListRequest} request
     * @param {TimeOffClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.hris.timeOff.list({
     *         approverId: "approver_id",
     *         createdAfter: new Date("2024-01-15T09:30:00.000Z"),
     *         createdBefore: new Date("2024-01-15T09:30:00.000Z"),
     *         cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
     *         employeeId: "employee_id",
     *         endedAfter: new Date("2024-01-15T09:30:00.000Z"),
     *         endedBefore: new Date("2024-01-15T09:30:00.000Z"),
     *         expand: "approver",
     *         includeDeletedData: true,
     *         includeRemoteData: true,
     *         includeShellData: true,
     *         modifiedAfter: new Date("2024-01-15T09:30:00.000Z"),
     *         modifiedBefore: new Date("2024-01-15T09:30:00.000Z"),
     *         pageSize: 1,
     *         remoteFields: "request_type",
     *         remoteId: "remote_id",
     *         requestType: "BEREAVEMENT",
     *         showEnumOrigins: "request_type",
     *         startedAfter: new Date("2024-01-15T09:30:00.000Z"),
     *         startedBefore: new Date("2024-01-15T09:30:00.000Z"),
     *         status: "APPROVED"
     *     })
     */
    public list(
        request: Merge.hris.TimeOffListRequest = {},
        requestOptions?: TimeOffClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.hris.PaginatedTimeOffList> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Merge.hris.TimeOffListRequest = {},
        requestOptions?: TimeOffClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.hris.PaginatedTimeOffList>> {
        const {
            approverId,
            createdAfter,
            createdBefore,
            cursor,
            employeeId,
            endedAfter,
            endedBefore,
            expand,
            includeDeletedData,
            includeRemoteData,
            includeShellData,
            modifiedAfter,
            modifiedBefore,
            pageSize,
            remoteFields,
            remoteId,
            requestType,
            showEnumOrigins,
            startedAfter,
            startedBefore,
            status,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (approverId != null) {
            _queryParams.approver_id = approverId;
        }

        if (createdAfter != null) {
            _queryParams.created_after = createdAfter.toISOString();
        }

        if (createdBefore != null) {
            _queryParams.created_before = createdBefore.toISOString();
        }

        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (employeeId != null) {
            _queryParams.employee_id = employeeId;
        }

        if (endedAfter != null) {
            _queryParams.ended_after = endedAfter.toISOString();
        }

        if (endedBefore != null) {
            _queryParams.ended_before = endedBefore.toISOString();
        }

        if (expand != null) {
            _queryParams.expand = serializers.hris.TimeOffListRequestExpand.jsonOrThrow(expand, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (includeDeletedData != null) {
            _queryParams.include_deleted_data = includeDeletedData.toString();
        }

        if (includeRemoteData != null) {
            _queryParams.include_remote_data = includeRemoteData.toString();
        }

        if (includeShellData != null) {
            _queryParams.include_shell_data = includeShellData.toString();
        }

        if (modifiedAfter != null) {
            _queryParams.modified_after = modifiedAfter.toISOString();
        }

        if (modifiedBefore != null) {
            _queryParams.modified_before = modifiedBefore.toISOString();
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (remoteFields != null) {
            _queryParams.remote_fields = serializers.hris.TimeOffListRequestRemoteFields.jsonOrThrow(remoteFields, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (remoteId != null) {
            _queryParams.remote_id = remoteId;
        }

        if (requestType != null) {
            _queryParams.request_type = serializers.hris.TimeOffListRequestRequestType.jsonOrThrow(requestType, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (showEnumOrigins != null) {
            _queryParams.show_enum_origins = serializers.hris.TimeOffListRequestShowEnumOrigins.jsonOrThrow(
                showEnumOrigins,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        if (startedAfter != null) {
            _queryParams.started_after = startedAfter.toISOString();
        }

        if (startedBefore != null) {
            _queryParams.started_before = startedBefore.toISOString();
        }

        if (status != null) {
            _queryParams.status = serializers.hris.TimeOffListRequestStatus.jsonOrThrow(status, {
                unrecognizedObjectKeys: "strip",
            });
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "hris/v1/time-off",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.hris.PaginatedTimeOffList.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /hris/v1/time-off.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a `TimeOff` object with the given values.
     *
     * @param {Merge.hris.TimeOffEndpointRequest} request
     * @param {TimeOffClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.hris.timeOff.create({
     *         isDebugMode: true,
     *         runAsync: true,
     *         model: {}
     *     })
     */
    public create(
        request: Merge.hris.TimeOffEndpointRequest,
        requestOptions?: TimeOffClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.hris.TimeOffResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Merge.hris.TimeOffEndpointRequest,
        requestOptions?: TimeOffClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.hris.TimeOffResponse>> {
        const { isDebugMode, runAsync, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (isDebugMode != null) {
            _queryParams.is_debug_mode = isDebugMode.toString();
        }

        if (runAsync != null) {
            _queryParams.run_async = runAsync.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "hris/v1/time-off",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.hris.TimeOffEndpointRequest.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.hris.TimeOffResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling POST /hris/v1/time-off.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns a `TimeOff` object with the given `id`.
     *
     * @param {string} id
     * @param {Merge.hris.TimeOffRetrieveRequest} request
     * @param {TimeOffClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.hris.timeOff.retrieve("id", {
     *         expand: "approver",
     *         includeRemoteData: true,
     *         includeShellData: true,
     *         remoteFields: "request_type",
     *         showEnumOrigins: "request_type"
     *     })
     */
    public retrieve(
        id: string,
        request: Merge.hris.TimeOffRetrieveRequest = {},
        requestOptions?: TimeOffClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.hris.TimeOff> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(id, request, requestOptions));
    }

    private async __retrieve(
        id: string,
        request: Merge.hris.TimeOffRetrieveRequest = {},
        requestOptions?: TimeOffClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.hris.TimeOff>> {
        const { expand, includeRemoteData, includeShellData, remoteFields, showEnumOrigins } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (expand != null) {
            _queryParams.expand = serializers.hris.TimeOffRetrieveRequestExpand.jsonOrThrow(expand, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (includeRemoteData != null) {
            _queryParams.include_remote_data = includeRemoteData.toString();
        }

        if (includeShellData != null) {
            _queryParams.include_shell_data = includeShellData.toString();
        }

        if (remoteFields != null) {
            _queryParams.remote_fields = serializers.hris.TimeOffRetrieveRequestRemoteFields.jsonOrThrow(remoteFields, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (showEnumOrigins != null) {
            _queryParams.show_enum_origins = serializers.hris.TimeOffRetrieveRequestShowEnumOrigins.jsonOrThrow(
                showEnumOrigins,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `hris/v1/time-off/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.hris.TimeOff.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /hris/v1/time-off/{id}.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns metadata for `TimeOff` POSTs.
     *
     * @param {TimeOffClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.hris.timeOff.metaPostRetrieve()
     */
    public metaPostRetrieve(
        requestOptions?: TimeOffClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.hris.MetaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__metaPostRetrieve(requestOptions));
    }

    private async __metaPostRetrieve(
        requestOptions?: TimeOffClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.hris.MetaResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "hris/v1/time-off/meta/post",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.hris.MetaResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /hris/v1/time-off/meta/post.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.apiKey)}`;
    }
}
