// This file was auto-generated by Fern from our API Definition.

export const ContactsBatchObjectsListRequestStatus = {
    Empty: "",
    Active: "ACTIVE",
    Archived: "ARCHIVED",
} as const;
export type ContactsBatchObjectsListRequestStatus =
    (typeof ContactsBatchObjectsListRequestStatus)[keyof typeof ContactsBatchObjectsListRequestStatus];
