// This file was auto-generated by Fern from our API Definition.

export const ContactsBatchObjectsListRequestExpandItem = {
    Addresses: "addresses",
    Company: "company",
    PhoneNumbers: "phone_numbers",
} as const;
export type ContactsBatchObjectsListRequestExpandItem =
    (typeof ContactsBatchObjectsListRequestExpandItem)[keyof typeof ContactsBatchObjectsListRequestExpandItem];
