// This file was auto-generated by Fern from our API Definition.

export const MessagesRepliesListRequestOrderBy = {
    RemoteCreatedAtDescending: "-remote_created_at",
    RemoteCreatedAtAscending: "remote_created_at",
} as const;
export type MessagesRepliesListRequestOrderBy =
    (typeof MessagesRepliesListRequestOrderBy)[keyof typeof MessagesRepliesListRequestOrderBy];
