// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const ContainersRetrieveRequestExpand: core.serialization.Schema<
    serializers.knowledgebase.ContainersRetrieveRequestExpand.Raw,
    Merge.knowledgebase.ContainersRetrieveRequestExpand
> = core.serialization.enum_([
    "parent_article",
    "parent_article,parent_container",
    "parent_container",
    "permissions",
    "permissions,parent_article",
    "permissions,parent_article,parent_container",
    "permissions,parent_container",
]);

export declare namespace ContainersRetrieveRequestExpand {
    export type Raw =
        | "parent_article"
        | "parent_article,parent_container"
        | "parent_container"
        | "permissions"
        | "permissions,parent_article"
        | "permissions,parent_article,parent_container"
        | "permissions,parent_container";
}
