/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * The user that is granted this permission.
 */
export type PermissionUser = string | Merge.filestorage.User;
