/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `JSON` - JSON
 * * `XML` - XML
 * * `MULTIPART` - MULTIPART
 */
export type RequestFormatEnum = "JSON" | "XML" | "MULTIPART";

export const RequestFormatEnum = {
    Json: "JSON",
    Xml: "XML",
    Multipart: "MULTIPART",
} as const;
