// This file was auto-generated by Fern from our API Definition.

export const CandidatesListRequestExpandItem = {
    Applications: "applications",
    Attachments: "attachments",
} as const;
export type CandidatesListRequestExpandItem =
    (typeof CandidatesListRequestExpandItem)[keyof typeof CandidatesListRequestExpandItem];
