/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const PayrollRunsListRequestRemoteFields: core.serialization.Schema<
    serializers.hris.PayrollRunsListRequestRemoteFields.Raw,
    Merge.hris.PayrollRunsListRequestRemoteFields
> = core.serialization.enum_(["run_state", "run_state,run_type", "run_type"]);

export declare namespace PayrollRunsListRequestRemoteFields {
    export type Raw = "run_state" | "run_state,run_type" | "run_type";
}
