/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `ONE_TO_ONE` - ONE_TO_ONE
 * * `MANY_TO_ONE` - MANY_TO_ONE
 * * `MANY_TO_MANY` - MANY_TO_MANY
 * * `ONE_TO_MANY` - ONE_TO_MANY
 */
export type CardinalityEnum = "ONE_TO_ONE" | "MANY_TO_ONE" | "MANY_TO_MANY" | "ONE_TO_MANY";
export const CardinalityEnum = {
    OneToOne: "ONE_TO_ONE",
    ManyToOne: "MANY_TO_ONE",
    ManyToMany: "MANY_TO_MANY",
    OneToMany: "ONE_TO_MANY",
} as const;
