/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * The type of value(s) that can be set for this condition.
 *
 * * `BOOLEAN` - BOOLEAN
 * * `DATE` - DATE
 * * `DATE_TIME` - DATE_TIME
 * * `INTEGER` - INTEGER
 * * `FLOAT` - FLOAT
 * * `STRING` - STRING
 * * `LIST_OF_STRINGS` - LIST_OF_STRINGS
 */
export type ConditionSchemaConditionType = Merge.crm.ConditionTypeEnum | string;
