// This file was auto-generated by Fern from our API Definition.

/**
 * * `string` - string
 * * `number` - number
 * * `date` - date
 * * `datetime` - datetime
 * * `bool` - bool
 * * `list` - list
 */
export const FieldTypeEnum = {
    String: "string",
    Number: "number",
    Date: "date",
    Datetime: "datetime",
    Bool: "bool",
    List: "list",
} as const;
export type FieldTypeEnum = (typeof FieldTypeEnum)[keyof typeof FieldTypeEnum];
