// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

export type RemoteFieldClassForCustomObjectClassFieldType = Merge.crm.FieldTypeEnum | string;
