// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

export interface WarningValidationProblem {
    source?: Merge.crm.ValidationProblemSource;
    title: string;
    detail: string;
    problemType: string;
}
