/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import * as Merge from "../../../../../../../api";
import * as core from "../../../../../../../core";

export const TicketingContactEndpointRequest: core.serialization.Schema<
    serializers.ticketing.TicketingContactEndpointRequest.Raw,
    Omit<Merge.ticketing.TicketingContactEndpointRequest, "isDebugMode" | "runAsync">
> = core.serialization.object({
    model: core.serialization.lazyObject(async () => (await import("../../../../../..")).ticketing.ContactRequest),
});

export declare namespace TicketingContactEndpointRequest {
    interface Raw {
        model: serializers.ticketing.ContactRequest.Raw;
    }
}
