/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Merge from "../../../../../index";
import * as serializers from "../../../../../../serialization/index";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers";
import * as errors from "../../../../../../errors/index";

export declare namespace Opportunities {
    export interface Options {
        environment?: core.Supplier<environments.MergeEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<core.BearerToken>;
        /** Override the X-Account-Token header */
        accountToken?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Account-Token header */
        accountToken?: string | undefined;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Opportunities {
    protected readonly _options: Opportunities.Options;

    constructor(_options: Opportunities.Options) {
        this._options = _options;
    }

    /**
     * Returns a list of `Opportunity` objects.{/* BEGIN_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="GET" data="H4sIAAAAAAAAE+1YYW/iOBD9K8gfUSDXsnSvSKcTC9yWSgk9mu1dd1VFgzMkBidObQdaVvvfTwmBlr1ud5F8NHfXTxAzebbfG78Z/JlQ0BgKeU86hMqYWCQWAXLSIaM0FVJnCdP3xCKQMhdiJB3ioAyx1hs7te7FkFhEZUUgBr8x5IE6kzglHWLHeVgjS9iUYWBHkimbigVKCNHevtKYFu8Qi3CWzDHoUiqyRD8Hsg5swDryq8f8Z6WJRVJQSkdSZGE0xtsM1bcw54lYcgxCbExArVfGMcZEA28EoMF+hNSQa6inxvI9BMhRY9AHDX3USDUTSTlrpHWqOrYdIU+bxQqaAS5sTGyQmlGOym63To/fnrYbJUox+69+yH85qs9uJ2Lytu6HlPuQ1R2P3rnecOnOwjdu782du/rQdlfzlTub/1T3Q6g7ntMeedetUb97NHoiwL88+fP06l3/3blbp6tBy51dL12PHjkenU9Ww9b5e7o8P/v9zl1dHzv9Dy3XG7TP34ujUW+snN5YON1mk1iEJRpDCfk2Fel8+vx4oEyWLqXIxW7sMIYQH3GyFgRS1kizCWe0qVpNiGElEliqJhWxHWPAwL7goKdCxlBg+uo2A4nNNAk31DORbHknHTJwz7pub9DfTYfuAhiHCUfS0TLDv+Uv6XwiZTblaR+XXygXCv0ANBazKSpZWsxjEQ5K+0A1WzB970MeneS7t0giNOaJIZYJSmIRibHQ6FOJoDFYh5Zjudq7T34KOnoYYkF+1nRO3U0+eJsxicEFSIhRo8zXffPFeloDzRbYgzgFFiZmtNjF3GgxSw+ixY/Sb5j24lNnam/+p1NWuqgJ5ku0w+T/V4m8B2t7ktSDVGUczTpFCfrqEd+nP1+6YfJzyENZwjPUvzCxIk2L6U0yW2BWgNrKW+9ZNrlMhTZD/1k2UanQ3y92btcbXg0qYCkPHbyvQc0N6bLt2c3pNEwUCyPNDdXILdy/oUmsyFFxGJVCiamu9e8TiBlVtdZJu3YJvMglg/a1wW+dtAv06oh0mPNjQCw30ypCzs0Is0GrgAKVPyYXLMVAsoXhZmkL+wJl5b9USHIeOUuMdVwbuOp6VDWORWHkUw7S8Ll4wH2RdrfydrTmR0j6j/Ce4z6T8q997t5yZSHI3tgxK5bKUamMX03qefY9hJgjBKaqwwNedSivENVLIec148m+QfZ7Y+fA98477Fczxa80C01fNy0KzOqYy8GK8p7cf8QkQDWvXRr7Y7ZRoET2f17qY8/741AaVP3S+qOIhHmDWYlI/FAx/f+2P9/W6ebLX2xd5ntSIAAA" /></Footer>{/* END_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}
     *
     * @param {Merge.crm.ListOpportunitiesRequest} request
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.list({
     *         cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw"
     *     })
     */
    public list(
        request: Merge.crm.ListOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.PaginatedOpportunityList> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Merge.crm.ListOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.PaginatedOpportunityList>> {
        const {
            accountId,
            createdAfter,
            createdBefore,
            cursor,
            expand,
            includeDeletedData,
            includeRemoteData,
            includeRemoteFields,
            includeShellData,
            modifiedAfter,
            modifiedBefore,
            ownerId,
            pageSize,
            remoteCreatedAfter,
            remoteFields,
            remoteId,
            showEnumOrigins,
            stageId,
            status,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (accountId != null) {
            _queryParams["account_id"] = accountId;
        }

        if (createdAfter != null) {
            _queryParams["created_after"] = createdAfter.toISOString();
        }

        if (createdBefore != null) {
            _queryParams["created_before"] = createdBefore.toISOString();
        }

        if (cursor != null) {
            _queryParams["cursor"] = cursor;
        }

        if (expand != null) {
            _queryParams["expand"] = serializers.crm.ListOpportunitiesRequestExpand.jsonOrThrow(expand, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (includeDeletedData != null) {
            _queryParams["include_deleted_data"] = includeDeletedData.toString();
        }

        if (includeRemoteData != null) {
            _queryParams["include_remote_data"] = includeRemoteData.toString();
        }

        if (includeRemoteFields != null) {
            _queryParams["include_remote_fields"] = includeRemoteFields.toString();
        }

        if (includeShellData != null) {
            _queryParams["include_shell_data"] = includeShellData.toString();
        }

        if (modifiedAfter != null) {
            _queryParams["modified_after"] = modifiedAfter.toISOString();
        }

        if (modifiedBefore != null) {
            _queryParams["modified_before"] = modifiedBefore.toISOString();
        }

        if (ownerId != null) {
            _queryParams["owner_id"] = ownerId;
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        if (remoteCreatedAfter !== undefined) {
            _queryParams["remote_created_after"] = remoteCreatedAfter?.toISOString() ?? null;
        }

        if (remoteFields != null) {
            _queryParams["remote_fields"] = remoteFields;
        }

        if (remoteId !== undefined) {
            _queryParams["remote_id"] = remoteId;
        }

        if (showEnumOrigins != null) {
            _queryParams["show_enum_origins"] = showEnumOrigins;
        }

        if (stageId != null) {
            _queryParams["stage_id"] = stageId;
        }

        if (status !== undefined) {
            _queryParams["status"] = serializers.crm.ListOpportunitiesRequestStatus.jsonOrThrow(status, {
                unrecognizedObjectKeys: "strip",
            });
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "crm/v1/opportunities",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.PaginatedOpportunityList.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /crm/v1/opportunities.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates an `Opportunity` object with the given values.{/* BEGIN_CRM_OPPORTUNITY_CREATE_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="POST" data="H4sIAAAAAAAAE91YYW/aOhT9K8gfUUhey+hekaYnBrxBpYS+NuteN1XRxb4Eg2OntgOFaf/9KSFlZWvXrkrbvX2CONfH9jnnHiM+EwoWY6VXpE2oTohDEsVQkDYZpanSNpPcrohDIOUBJEjaxEcdY6174tc6x0PiEJMVhcj+5iiYGWickDbxkryskUk+4ci8qebGo2qBGmL0tlMak2IOcYjgco6sQ6nKpP0RyKawAZvKbx7z18YSh6RgjJ1qlcXTE7zM0NyFOZdqKZDF2BiD2exMYILSgmgwsODdQGroDdRtY/kZGAq0yHpgoYcWqeVKlqtOrU1N2/OmKFK32IHLcOGh9EBbTgUar9U83H992GqUKMXqf0WxeLNXn12O1fh1PYqpiCCr+yG9CsLhMpjFr4Luq6tg/b4VrOfrYDb/ox7FUPdDvzUKz5ujXmdvdEtBdHrw7+HZ297bo6BO1/1mMDtfBiHd80M6H6+HzaN3dHk0+OcqWJ/v+733zSDst47eqb1R98T43RPld1yXOIRLi7GG/JiGtD99vjlQmqVDLV9gF5IUeCx35wwTiPEGNxthIOWNNBsLTl3TdCGBtZKwNC5ViZcg4+DtYkbmMgON7iyNryXgSm75J23SDwadoNvv7dqiswAuYCyQtK3O8Dsfk/YnUroqt39SfmFoqOZpAe0QAcZGkO+H21UEeYHMD+4QtZSoiUM0JspiRDWCRbYpKcc4y7vH5iQUnzYz5CJ/e5lxjewYNCRoUedbufji3EZvF1KTCayG12MBdqJ0UoK6qXwBRh9F30+yNsjGp6my1bA2yMYmVfZ+GwadcHjWr4QyKpTBiIHFah25TeNHOHQXw735FFEBxny7jLsAkSG5Q6OhNDyeWrGqRqUt3LVOz2Tup1KqguzwOdXKqImt9VYSEk5NrXnQqp2CQFNtoFzjNw9aBfqTavAA5p8jY455ikzzRcXZvIV9gaB5uWgpl6k2YQorTpSmFUv0FfcHBv/dL4P7u++RYm7b8XZRQ4REILDicBWI+hXvF7gxnvV6OLM8rorF69ZYFJi/3xX8kDa4g+aPKBmaee0UhaiW7BI5+nNp98Pww3PR/eSc7qDdxaqaqvwvimoZXaupojq537//g3R/0C+biy//AVfgGZQgEgAA" /></Footer>{/* END_CRM_OPPORTUNITY_CREATE_SUPPORTED_FIELDS * /}
     *
     * @param {Merge.crm.OpportunityEndpointRequest} request
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.create({
     *         model: {}
     *     })
     */
    public create(
        request: Merge.crm.OpportunityEndpointRequest,
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.OpportunityResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Merge.crm.OpportunityEndpointRequest,
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.OpportunityResponse>> {
        const { isDebugMode, runAsync, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (isDebugMode != null) {
            _queryParams["is_debug_mode"] = isDebugMode.toString();
        }

        if (runAsync != null) {
            _queryParams["run_async"] = runAsync.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "crm/v1/opportunities",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.crm.OpportunityEndpointRequest.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.OpportunityResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling POST /crm/v1/opportunities.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns an `Opportunity` object with the given `id`.{/* BEGIN_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="GET" data="H4sIAAAAAAAAE+1YYW/iOBD9K8gfUSDXsnSvSKcTC9yWSgk9mu1dd1VFgzMkBidObQdaVvvfTwmBlr1ud5F8NHfXTxAzebbfG78Z/JlQ0BgKeU86hMqYWCQWAXLSIaM0FVJnCdP3xCKQMhdiJB3ioAyx1hs7te7FkFhEZUUgBr8x5IE6kzglHWLHeVgjS9iUYWBHkimbigVKCNHevtKYFu8Qi3CWzDHoUiqyRD8Hsg5swDryq8f8Z6WJRVJQSkdSZGE0xtsM1bcw54lYcgxCbExArVfGMcZEA28EoMF+hNSQa6inxvI9BMhRY9AHDX3USDUTSTlrpHWqOrYdIU+bxQqaAS5sTGyQmlGOym63To/fnrYbJUox+69+yH85qs9uJ2Lytu6HlPuQ1R2P3rnecOnOwjdu782du/rQdlfzlTub/1T3Q6g7ntMeedetUb97NHoiwL88+fP06l3/3blbp6tBy51dL12PHjkenU9Ww9b5e7o8P/v9zl1dHzv9Dy3XG7TP34ujUW+snN5YON1mk1iEJRpDCfk2Fel8+vx4oEyWLqXIxW7sMIYQH3GyFgRS1kizCWe0qVpNiGElEliqJhWxHWPAwL7goKdCxlBg+uo2A4nNNAk31DORbHknHTJwz7pub9DfTYfuAhiHCUfS0TLDv+Uv6XwiZTblaR+XXygXCv0ANBazKSpZWsxjEQ5K+0A1WzB970MeneS7t0giNOaJIZYJSmIRibHQ6FOJoDFYh5Zjudq7T34KOnoYYkF+1nRO3U0+eJsxicEFSIhRo8zXffPFeloDzRbYgzgFFiZmtNjF3GgxSw+ixY/Sb5j24lNnam/+p1NWuqgJ5ku0w+T/V4m8B2t7ktSDVGUczTpFCfrqEd+nP1+6YfJzyENZwjPUvzCxIk2L6U0yW2BWgNrKW+9ZNrlMhTZD/1k2UanQ3y92btcbXg0qYCkPHbyvQc0N6bLt2c3pNEwUCyPNDdXILdy/oUmsyFFxGJVCiamu9e8TiBlVtdZJu3YJvMglg/a1wW+dtAv06oh0mPNjQCw30ypCzs0Is0GrgAKVPyYXLMVAsoXhZmkL+wJl5b9USHIeOUuMdVwbuOp6VDWORWHkUw7S8Ll4wH2RdrfydrTmR0j6j/Ce4z6T8q997t5yZSHI3tgxK5bKUamMX03qefY9hJgjBKaqwwNedSivENVLIec148m+QfZ7Y+fA98477Fczxa80C01fNy0KzOqYy8GK8p7cf8QkQDWvXRr7Y7ZRoET2f17qY8/741AaVP3S+qOIhHmDWYlI/FAx/f+2P9/W6ebLX2xd5ntSIAAA" /></Footer>{/* END_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}
     *
     * @param {string} id
     * @param {Merge.crm.RetrieveOpportunitiesRequest} request
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.retrieve("id")
     */
    public retrieve(
        id: string,
        request: Merge.crm.RetrieveOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.Opportunity> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(id, request, requestOptions));
    }

    private async __retrieve(
        id: string,
        request: Merge.crm.RetrieveOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.Opportunity>> {
        const { expand, includeRemoteData, includeRemoteFields, includeShellData, remoteFields, showEnumOrigins } =
            request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (expand != null) {
            _queryParams["expand"] = serializers.crm.RetrieveOpportunitiesRequestExpand.jsonOrThrow(expand, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (includeRemoteData != null) {
            _queryParams["include_remote_data"] = includeRemoteData.toString();
        }

        if (includeRemoteFields != null) {
            _queryParams["include_remote_fields"] = includeRemoteFields.toString();
        }

        if (includeShellData != null) {
            _queryParams["include_shell_data"] = includeShellData.toString();
        }

        if (remoteFields != null) {
            _queryParams["remote_fields"] = remoteFields;
        }

        if (showEnumOrigins != null) {
            _queryParams["show_enum_origins"] = showEnumOrigins;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `crm/v1/opportunities/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.Opportunity.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /crm/v1/opportunities/{id}.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Updates an `Opportunity` object with the given `id`.{/* BEGIN_CRM_OPPORTUNITY_EDIT_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="EDIT" data="H4sIAAAAAAAAE+VWYW/aMBD9K9N9RCFZx9jUSNPEgA2QEljLqnVVFR3OEQxObGwHWqr+9ymBsbZru26jqqp9smzfvfO9dz77AhhaSqQ+Bx+YTsGBVMYkwIe+UlLbPOP2HBxAxUNMCXwISCf0onkQvGgMuuCAyUtDij9yErHpaBqDD15amFXzjI85xd5Ec+MxuSCNCXlbl+q49AEHBM9mFDcYk3lm7wNZG1ZxbXljWmwbCw4oNMZOtMyTyQHNczJ3Yc4yuRQUJ1QdoVmfTFBKmUVRjdGidwWpqtdQt60VOcQkyFLcQostssQsl9km6sRaZXzPm5BQbnkCN6aFR5mH2nImyHj12v6rt/v16galjP4+SsS7vcp0PpKjt5UoYSLCvBIM2Vk47C7DafI6bL4+C1df6uFqtgqns5eVKMFKMAzq/eFxrd9q7PVvMYgO33zdP/rQ+tALK2zVroXT42U4ZHvBkM1Gq26t94kte53PZ+Hq+FXQ+lILh+1675Pc6zcPTNA8kEHDdcEBnllKNBZpGvBPLq4ubIqlicrkgq4bd1NM6Aopa0VQ8arKR4Iz19RcTHElM1wal8nUSynm6A0E2rHU6QbUVVnyg3Uusy3l4EM77DTCZrt1vRIaC+QCR4LAtzqnX0oX/BPAtKgjcIAJaSiK0VIZwzDNVYnuQFbk5oBcZqTBAU2ptBQxTWgpjrDwNrZI8bTYnOdcUzxAjSlZ0kWU00vnVrKkUiXiLrkqMd2pegSq1neuaA5/TRqPt2SVo83Nn7LWyUeHStrd0NbJR0ZJG5l5jpruoS1sDLtH7ccmTaCxETLLF9yeryvrAcW3Wdv21gfye93PvTqLmEBjbkK7CxQ5wR26DLiiWPPFji//FvYJxHnOchyiIDMWqHesx0/cJ2ky/yTJDrrPOn2p2aPQWuDe88z9l03oDiG+yYksfqW7lWElJ5Lp9Md78Dyl+N1n5PTyOzQjv10HDAAA" /></Footer>{/* END_CRM_OPPORTUNITY_EDIT_SUPPORTED_FIELDS * /}
     *
     * @param {string} id
     * @param {Merge.crm.PatchedOpportunityEndpointRequest} request
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.partialUpdate("id", {
     *         model: {}
     *     })
     */
    public partialUpdate(
        id: string,
        request: Merge.crm.PatchedOpportunityEndpointRequest,
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.OpportunityResponse> {
        return core.HttpResponsePromise.fromPromise(this.__partialUpdate(id, request, requestOptions));
    }

    private async __partialUpdate(
        id: string,
        request: Merge.crm.PatchedOpportunityEndpointRequest,
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.OpportunityResponse>> {
        const { isDebugMode, runAsync, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (isDebugMode != null) {
            _queryParams["is_debug_mode"] = isDebugMode.toString();
        }

        if (runAsync != null) {
            _queryParams["run_async"] = runAsync.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `crm/v1/opportunities/${encodeURIComponent(id)}`,
            ),
            method: "PATCH",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.crm.PatchedOpportunityEndpointRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.OpportunityResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling PATCH /crm/v1/opportunities/{id}.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns metadata for `Opportunity` PATCHs.{/* BEGIN_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="GET" data="H4sIAAAAAAAAE+1YYW/iOBD9K8gfUSDXsnSvSKcTC9yWSgk9mu1dd1VFgzMkBidObQdaVvvfTwmBlr1ud5F8NHfXTxAzebbfG78Z/JlQ0BgKeU86hMqYWCQWAXLSIaM0FVJnCdP3xCKQMhdiJB3ioAyx1hs7te7FkFhEZUUgBr8x5IE6kzglHWLHeVgjS9iUYWBHkimbigVKCNHevtKYFu8Qi3CWzDHoUiqyRD8Hsg5swDryq8f8Z6WJRVJQSkdSZGE0xtsM1bcw54lYcgxCbExArVfGMcZEA28EoMF+hNSQa6inxvI9BMhRY9AHDX3USDUTSTlrpHWqOrYdIU+bxQqaAS5sTGyQmlGOym63To/fnrYbJUox+69+yH85qs9uJ2Lytu6HlPuQ1R2P3rnecOnOwjdu782du/rQdlfzlTub/1T3Q6g7ntMeedetUb97NHoiwL88+fP06l3/3blbp6tBy51dL12PHjkenU9Ww9b5e7o8P/v9zl1dHzv9Dy3XG7TP34ujUW+snN5YON1mk1iEJRpDCfk2Fel8+vx4oEyWLqXIxW7sMIYQH3GyFgRS1kizCWe0qVpNiGElEliqJhWxHWPAwL7goKdCxlBg+uo2A4nNNAk31DORbHknHTJwz7pub9DfTYfuAhiHCUfS0TLDv+Uv6XwiZTblaR+XXygXCv0ANBazKSpZWsxjEQ5K+0A1WzB970MeneS7t0giNOaJIZYJSmIRibHQ6FOJoDFYh5Zjudq7T34KOnoYYkF+1nRO3U0+eJsxicEFSIhRo8zXffPFeloDzRbYgzgFFiZmtNjF3GgxSw+ixY/Sb5j24lNnam/+p1NWuqgJ5ku0w+T/V4m8B2t7ktSDVGUczTpFCfrqEd+nP1+6YfJzyENZwjPUvzCxIk2L6U0yW2BWgNrKW+9ZNrlMhTZD/1k2UanQ3y92btcbXg0qYCkPHbyvQc0N6bLt2c3pNEwUCyPNDdXILdy/oUmsyFFxGJVCiamu9e8TiBlVtdZJu3YJvMglg/a1wW+dtAv06oh0mPNjQCw30ypCzs0Is0GrgAKVPyYXLMVAsoXhZmkL+wJl5b9USHIeOUuMdVwbuOp6VDWORWHkUw7S8Ll4wH2RdrfydrTmR0j6j/Ce4z6T8q997t5yZSHI3tgxK5bKUamMX03qefY9hJgjBKaqwwNedSivENVLIec148m+QfZ7Y+fA98477Fczxa80C01fNy0KzOqYy8GK8p7cf8QkQDWvXRr7Y7ZRoET2f17qY8/741AaVP3S+qOIhHmDWYlI/FAx/f+2P9/W6ebLX2xd5ntSIAAA" /></Footer>{/* END_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}
     *
     * @param {string} id
     * @param {Merge.crm.MetaPatchRetrieveOpportunitiesRequest} request
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.metaPatchRetrieve("id")
     */
    public metaPatchRetrieve(
        id: string,
        request: Merge.crm.MetaPatchRetrieveOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.MetaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__metaPatchRetrieve(id, request, requestOptions));
    }

    private async __metaPatchRetrieve(
        id: string,
        request: Merge.crm.MetaPatchRetrieveOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.MetaResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `crm/v1/opportunities/meta/patch/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.MetaResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError(
                    "Timeout exceeded when calling GET /crm/v1/opportunities/meta/patch/{id}.",
                );
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns metadata for `Opportunity` POSTs.{/* BEGIN_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="GET" data="H4sIAAAAAAAAE+1YYW/iOBD9K8gfUSDXsnSvSKcTC9yWSgk9mu1dd1VFgzMkBidObQdaVvvfTwmBlr1ud5F8NHfXTxAzebbfG78Z/JlQ0BgKeU86hMqYWCQWAXLSIaM0FVJnCdP3xCKQMhdiJB3ioAyx1hs7te7FkFhEZUUgBr8x5IE6kzglHWLHeVgjS9iUYWBHkimbigVKCNHevtKYFu8Qi3CWzDHoUiqyRD8Hsg5swDryq8f8Z6WJRVJQSkdSZGE0xtsM1bcw54lYcgxCbExArVfGMcZEA28EoMF+hNSQa6inxvI9BMhRY9AHDX3USDUTSTlrpHWqOrYdIU+bxQqaAS5sTGyQmlGOym63To/fnrYbJUox+69+yH85qs9uJ2Lytu6HlPuQ1R2P3rnecOnOwjdu782du/rQdlfzlTub/1T3Q6g7ntMeedetUb97NHoiwL88+fP06l3/3blbp6tBy51dL12PHjkenU9Ww9b5e7o8P/v9zl1dHzv9Dy3XG7TP34ujUW+snN5YON1mk1iEJRpDCfk2Fel8+vx4oEyWLqXIxW7sMIYQH3GyFgRS1kizCWe0qVpNiGElEliqJhWxHWPAwL7goKdCxlBg+uo2A4nNNAk31DORbHknHTJwz7pub9DfTYfuAhiHCUfS0TLDv+Uv6XwiZTblaR+XXygXCv0ANBazKSpZWsxjEQ5K+0A1WzB970MeneS7t0giNOaJIZYJSmIRibHQ6FOJoDFYh5Zjudq7T34KOnoYYkF+1nRO3U0+eJsxicEFSIhRo8zXffPFeloDzRbYgzgFFiZmtNjF3GgxSw+ixY/Sb5j24lNnam/+p1NWuqgJ5ku0w+T/V4m8B2t7ktSDVGUczTpFCfrqEd+nP1+6YfJzyENZwjPUvzCxIk2L6U0yW2BWgNrKW+9ZNrlMhTZD/1k2UanQ3y92btcbXg0qYCkPHbyvQc0N6bLt2c3pNEwUCyPNDdXILdy/oUmsyFFxGJVCiamu9e8TiBlVtdZJu3YJvMglg/a1wW+dtAv06oh0mPNjQCw30ypCzs0Is0GrgAKVPyYXLMVAsoXhZmkL+wJl5b9USHIeOUuMdVwbuOp6VDWORWHkUw7S8Ll4wH2RdrfydrTmR0j6j/Ce4z6T8q997t5yZSHI3tgxK5bKUamMX03qefY9hJgjBKaqwwNedSivENVLIec148m+QfZ7Y+fA98477Fczxa80C01fNy0KzOqYy8GK8p7cf8QkQDWvXRr7Y7ZRoET2f17qY8/741AaVP3S+qOIhHmDWYlI/FAx/f+2P9/W6ebLX2xd5ntSIAAA" /></Footer>{/* END_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}
     *
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.metaPostRetrieve()
     */
    public metaPostRetrieve(
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.MetaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__metaPostRetrieve(requestOptions));
    }

    private async __metaPostRetrieve(
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.MetaResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "crm/v1/opportunities/meta/post",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.MetaResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError(
                    "Timeout exceeded when calling GET /crm/v1/opportunities/meta/post.",
                );
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns a list of `RemoteFieldClass` objects.{/* BEGIN_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="GET" data="H4sIAAAAAAAAE+1YYW/iOBD9K8gfUSDXsnSvSKcTC9yWSgk9mu1dd1VFgzMkBidObQdaVvvfTwmBlr1ud5F8NHfXTxAzebbfG78Z/JlQ0BgKeU86hMqYWCQWAXLSIaM0FVJnCdP3xCKQMhdiJB3ioAyx1hs7te7FkFhEZUUgBr8x5IE6kzglHWLHeVgjS9iUYWBHkimbigVKCNHevtKYFu8Qi3CWzDHoUiqyRD8Hsg5swDryq8f8Z6WJRVJQSkdSZGE0xtsM1bcw54lYcgxCbExArVfGMcZEA28EoMF+hNSQa6inxvI9BMhRY9AHDX3USDUTSTlrpHWqOrYdIU+bxQqaAS5sTGyQmlGOym63To/fnrYbJUox+69+yH85qs9uJ2Lytu6HlPuQ1R2P3rnecOnOwjdu782du/rQdlfzlTub/1T3Q6g7ntMeedetUb97NHoiwL88+fP06l3/3blbp6tBy51dL12PHjkenU9Ww9b5e7o8P/v9zl1dHzv9Dy3XG7TP34ujUW+snN5YON1mk1iEJRpDCfk2Fel8+vx4oEyWLqXIxW7sMIYQH3GyFgRS1kizCWe0qVpNiGElEliqJhWxHWPAwL7goKdCxlBg+uo2A4nNNAk31DORbHknHTJwz7pub9DfTYfuAhiHCUfS0TLDv+Uv6XwiZTblaR+XXygXCv0ANBazKSpZWsxjEQ5K+0A1WzB970MeneS7t0giNOaJIZYJSmIRibHQ6FOJoDFYh5Zjudq7T34KOnoYYkF+1nRO3U0+eJsxicEFSIhRo8zXffPFeloDzRbYgzgFFiZmtNjF3GgxSw+ixY/Sb5j24lNnam/+p1NWuqgJ5ku0w+T/V4m8B2t7ktSDVGUczTpFCfrqEd+nP1+6YfJzyENZwjPUvzCxIk2L6U0yW2BWgNrKW+9ZNrlMhTZD/1k2UanQ3y92btcbXg0qYCkPHbyvQc0N6bLt2c3pNEwUCyPNDdXILdy/oUmsyFFxGJVCiamu9e8TiBlVtdZJu3YJvMglg/a1wW+dtAv06oh0mPNjQCw30ypCzs0Is0GrgAKVPyYXLMVAsoXhZmkL+wJl5b9USHIeOUuMdVwbuOp6VDWORWHkUw7S8Ll4wH2RdrfydrTmR0j6j/Ce4z6T8q997t5yZSHI3tgxK5bKUamMX03qefY9hJgjBKaqwwNedSivENVLIec148m+QfZ7Y+fA98477Fczxa80C01fNy0KzOqYy8GK8p7cf8QkQDWvXRr7Y7ZRoET2f17qY8/741AaVP3S+qOIhHmDWYlI/FAx/f+2P9/W6ebLX2xd5ntSIAAA" /></Footer>{/* END_CRM_OPPORTUNITY_FETCH_SUPPORTED_FIELDS * /}
     *
     * @param {Merge.crm.RemoteFieldClassesListOpportunitiesRequest} request
     * @param {Opportunities.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.opportunities.remoteFieldClassesList({
     *         cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw"
     *     })
     */
    public remoteFieldClassesList(
        request: Merge.crm.RemoteFieldClassesListOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.PaginatedRemoteFieldClassList> {
        return core.HttpResponsePromise.fromPromise(this.__remoteFieldClassesList(request, requestOptions));
    }

    private async __remoteFieldClassesList(
        request: Merge.crm.RemoteFieldClassesListOpportunitiesRequest = {},
        requestOptions?: Opportunities.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.PaginatedRemoteFieldClassList>> {
        const {
            cursor,
            includeDeletedData,
            includeRemoteData,
            includeRemoteFields,
            includeShellData,
            isCommonModelField,
            isCustom,
            pageSize,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams["cursor"] = cursor;
        }

        if (includeDeletedData != null) {
            _queryParams["include_deleted_data"] = includeDeletedData.toString();
        }

        if (includeRemoteData != null) {
            _queryParams["include_remote_data"] = includeRemoteData.toString();
        }

        if (includeRemoteFields != null) {
            _queryParams["include_remote_fields"] = includeRemoteFields.toString();
        }

        if (includeShellData != null) {
            _queryParams["include_shell_data"] = includeShellData.toString();
        }

        if (isCommonModelField !== undefined) {
            _queryParams["is_common_model_field"] = isCommonModelField?.toString() ?? null;
        }

        if (isCustom !== undefined) {
            _queryParams["is_custom"] = isCustom?.toString() ?? null;
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "crm/v1/opportunities/remote-field-classes",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.PaginatedRemoteFieldClassList.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError(
                    "Timeout exceeded when calling GET /crm/v1/opportunities/remote-field-classes.",
                );
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.apiKey)}`;
    }
}
