// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { User } from "./User";

export const AccountRequestOwner: core.serialization.Schema<
    serializers.crm.AccountRequestOwner.Raw,
    Merge.crm.AccountRequestOwner
> = core.serialization.undiscriminatedUnion([core.serialization.string(), User]);

export declare namespace AccountRequestOwner {
    export type Raw = string | User.Raw;
}
