// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const AddressTypeEnum: core.serialization.Schema<
    serializers.crm.AddressTypeEnum.Raw,
    Merge.crm.AddressTypeEnum
> = core.serialization.enum_(["BILLING", "SHIPPING"]);

export declare namespace AddressTypeEnum {
    export type Raw = "BILLING" | "SHIPPING";
}
