/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const CardinalityEnum: core.serialization.Schema<
    serializers.crm.CardinalityEnum.Raw,
    Merge.crm.CardinalityEnum
> = core.serialization.enum_(["ONE_TO_ONE", "MANY_TO_ONE", "MANY_TO_MANY", "ONE_TO_MANY"]);

export declare namespace CardinalityEnum {
    type Raw = "ONE_TO_ONE" | "MANY_TO_ONE" | "MANY_TO_MANY" | "ONE_TO_MANY";
}
