/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";

export const EmailAddressRequest: core.serialization.ObjectSchema<
    serializers.crm.EmailAddressRequest.Raw,
    Merge.crm.EmailAddressRequest
> = core.serialization.object({
    emailAddress: core.serialization.property("email_address", core.serialization.string().optionalNullable()),
    emailAddressType: core.serialization.property("email_address_type", core.serialization.string().optionalNullable()),
    integrationParams: core.serialization.property(
        "integration_params",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
    linkedAccountParams: core.serialization.property(
        "linked_account_params",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
});

export declare namespace EmailAddressRequest {
    export interface Raw {
        email_address?: (string | null) | null;
        email_address_type?: (string | null) | null;
        integration_params?: (Record<string, unknown> | null) | null;
        linked_account_params?: (Record<string, unknown> | null) | null;
    }
}
