// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const EnabledActionsEnum: core.serialization.Schema<
    serializers.crm.EnabledActionsEnum.Raw,
    Merge.crm.EnabledActionsEnum
> = core.serialization.enum_(["READ", "WRITE"]);

export declare namespace EnabledActionsEnum {
    export type Raw = "READ" | "WRITE";
}
