// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Account } from "./Account";

export const EngagementAccount: core.serialization.Schema<
    serializers.crm.EngagementAccount.Raw,
    Merge.crm.EngagementAccount
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Account]);

export declare namespace EngagementAccount {
    export type Raw = string | Account.Raw;
}
