/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { Contact } from "./Contact";

export const EngagementContactsItem: core.serialization.Schema<
    serializers.crm.EngagementContactsItem.Raw,
    Merge.crm.EngagementContactsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Contact]);

export declare namespace EngagementContactsItem {
    type Raw = string | Contact.Raw;
}
