/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const OpportunityResponse: core.serialization.ObjectSchema<
    serializers.crm.OpportunityResponse.Raw,
    Merge.crm.OpportunityResponse
> = core.serialization.object({
    model: core.serialization.lazyObject(async () => (await import("../../..")).crm.Opportunity),
    warnings: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).crm.WarningValidationProblem)
    ),
    errors: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).crm.ErrorValidationProblem)
    ),
    logs: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).crm.DebugModeLog))
        .optional(),
});

export declare namespace OpportunityResponse {
    interface Raw {
        model: serializers.crm.Opportunity.Raw;
        warnings: serializers.crm.WarningValidationProblem.Raw[];
        errors: serializers.crm.ErrorValidationProblem.Raw[];
        logs?: serializers.crm.DebugModeLog.Raw[] | null;
    }
}
