/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { Lead } from "./Lead";

export const PaginatedLeadList: core.serialization.ObjectSchema<
    serializers.crm.PaginatedLeadList.Raw,
    Merge.crm.PaginatedLeadList
> = core.serialization.object({
    next: core.serialization.string().optionalNullable(),
    previous: core.serialization.string().optionalNullable(),
    results: core.serialization.list(Lead).optional(),
});

export declare namespace PaginatedLeadList {
    export interface Raw {
        next?: (string | null) | null;
        previous?: (string | null) | null;
        results?: Lead.Raw[] | null;
    }
}
