/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { Stage } from "./Stage";

export const PaginatedStageList: core.serialization.ObjectSchema<
    serializers.crm.PaginatedStageList.Raw,
    Merge.crm.PaginatedStageList
> = core.serialization.object({
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization.list(Stage).optional(),
});

export declare namespace PaginatedStageList {
    export interface Raw {
        next?: string | null;
        previous?: string | null;
        results?: Stage.Raw[] | null;
    }
}
