/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const PaginatedLeadList: core.serialization.ObjectSchema<
    serializers.crm.PaginatedLeadList.Raw,
    Merge.crm.PaginatedLeadList
> = core.serialization.object({
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).crm.Lead))
        .optional(),
});

export declare namespace PaginatedLeadList {
    interface Raw {
        next?: string | null;
        previous?: string | null;
        results?: serializers.crm.Lead.Raw[] | null;
    }
}
