/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const PatchedAccountRequest: core.serialization.ObjectSchema<
    serializers.crm.PatchedAccountRequest.Raw,
    Merge.crm.PatchedAccountRequest
> = core.serialization.object({
    owner: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    industry: core.serialization.string().optional(),
    website: core.serialization.string().optional(),
    numberOfEmployees: core.serialization.property("number_of_employees", core.serialization.number().optional()),
    addresses: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).crm.AddressRequest))
        .optional(),
    lastActivityAt: core.serialization.property("last_activity_at", core.serialization.date().optional()),
    integrationParams: core.serialization.property(
        "integration_params",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    linkedAccountParams: core.serialization.property(
        "linked_account_params",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    remoteFields: core.serialization.property(
        "remote_fields",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).crm.RemoteFieldRequest))
            .optional()
    ),
});

export declare namespace PatchedAccountRequest {
    interface Raw {
        owner?: string | null;
        name?: string | null;
        description?: string | null;
        industry?: string | null;
        website?: string | null;
        number_of_employees?: number | null;
        addresses?: serializers.crm.AddressRequest.Raw[] | null;
        last_activity_at?: string | null;
        integration_params?: Record<string, unknown> | null;
        linked_account_params?: Record<string, unknown> | null;
        remote_fields?: serializers.crm.RemoteFieldRequest.Raw[] | null;
    }
}
