/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";

export const PhoneNumberRequest: core.serialization.ObjectSchema<
    serializers.crm.PhoneNumberRequest.Raw,
    Merge.crm.PhoneNumberRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optionalNullable()),
    phoneNumberType: core.serialization.property("phone_number_type", core.serialization.string().optionalNullable()),
    integrationParams: core.serialization.property(
        "integration_params",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
    linkedAccountParams: core.serialization.property(
        "linked_account_params",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
});

export declare namespace PhoneNumberRequest {
    export interface Raw {
        phone_number?: (string | null) | null;
        phone_number_type?: (string | null) | null;
        integration_params?: (Record<string, unknown> | null) | null;
        linked_account_params?: (Record<string, unknown> | null) | null;
    }
}
