// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const TaskStatusEnum: core.serialization.Schema<serializers.crm.TaskStatusEnum.Raw, Merge.crm.TaskStatusEnum> =
    core.serialization.enum_(["OPEN", "CLOSED"]);

export declare namespace TaskStatusEnum {
    export type Raw = "OPEN" | "CLOSED";
}
