export { type CustomObjectClassesCustomObjectsAssociationsListAssociationsRequest } from "./CustomObjectClassesCustomObjectsAssociationsListAssociationsRequest";
export { type CustomObjectClassesCustomObjectsAssociationsUpdateAssociationsRequest } from "./CustomObjectClassesCustomObjectsAssociationsUpdateAssociationsRequest";
