/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw"
 *     }
 */
export interface RemoteFieldClassesListContactsRequest {
    /**
     * The pagination cursor value.
     */
    cursor?: string;
    /**
     * Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. [Learn more](https://docs.merge.dev/integrations/hris/supported-features/).
     */
    includeDeletedData?: boolean;
    /**
     * Whether to include the original data Merge fetched from the third-party to produce these models.
     */
    includeRemoteData?: boolean;
    /**
     * Whether to include all remote fields, including fields that Merge did not map to common models, in a normalized format.
     */
    includeRemoteFields?: boolean;
    /**
     * Whether to include shell records. Shell records are empty records (they may contain some metadata but all other fields are null).
     */
    includeShellData?: boolean;
    /**
     * If provided, will only return remote field classes with this is_common_model_field value
     */
    isCommonModelField?: boolean | null;
    /**
     * If provided, will only return remote fields classes with this is_custom value
     */
    isCustom?: boolean | null;
    /**
     * Number of results to return per page. The maximum limit is 100.
     */
    pageSize?: number;
}
