// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";
import { VendorCreditRequest } from "../../../../types/VendorCreditRequest";

export const VendorCreditBulkEndpointRequest: core.serialization.Schema<
    serializers.accounting.VendorCreditBulkEndpointRequest.Raw,
    Omit<Merge.accounting.VendorCreditBulkEndpointRequest, "isDebugMode" | "runAsync">
> = core.serialization.object({
    model: VendorCreditRequest,
});

export declare namespace VendorCreditBulkEndpointRequest {
    export interface Raw {
        model: VendorCreditRequest.Raw;
    }
}
