// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const GroupsListRequestExpand: core.serialization.Schema<
    serializers.knowledgebase.GroupsListRequestExpand.Raw,
    Merge.knowledgebase.GroupsListRequestExpand
> = core.serialization.enum_(["parent_group", "users", "users,parent_group"]);

export declare namespace GroupsListRequestExpand {
    export type Raw = "parent_group" | "users" | "users,parent_group";
}
