// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const EmployeesListRequestEmploymentStatus: core.serialization.Schema<
    serializers.hris.EmployeesListRequestEmploymentStatus.Raw,
    Merge.hris.EmployeesListRequestEmploymentStatus
> = core.serialization.enum_(["ACTIVE", "INACTIVE", "PENDING"]);

export declare namespace EmployeesListRequestEmploymentStatus {
    export type Raw = "ACTIVE" | "INACTIVE" | "PENDING";
}
