// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";
import { FolderRequest } from "../../../../types/FolderRequest";

export const FileStorageFolderEndpointRequest: core.serialization.Schema<
    serializers.fileStorage.FileStorageFolderEndpointRequest.Raw,
    Omit<Merge.fileStorage.FileStorageFolderEndpointRequest, "isDebugMode" | "runAsync">
> = core.serialization.object({
    model: FolderRequest,
});

export declare namespace FileStorageFolderEndpointRequest {
    export interface Raw {
        model: FolderRequest.Raw;
    }
}
