// This file was auto-generated by Fern from our API Definition.

import { MergeClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("LinkedAccountsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new MergeClient({
            maxRetries: 0,
            apiKey: "test",
            accountToken: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            next: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
            previous: "cj1sZXdwd2VycWVtY29zZnNkc2NzUWxNMEUxTXk0ME16UXpNallsTWtJ",
            results: [
                {
                    id: "e59b1821-f85c-4e28-a6b3-1804156f3563",
                    category: "hris",
                    status: "COMPLETE",
                    status_detail: "Invalid login credentials",
                    end_user_origin_id: "3ac95cde-6c7f-4eef-afec-be710b42308d",
                    end_user_organization_name: "Foo Bar, LLC",
                    end_user_email_address: "hradmin@foobar.dev",
                    subdomain: "foobar",
                    webhook_listener_url: "https://api.merge.dev/api/integrations/webhook-listener/7fc3mee0UW8ecV4",
                    is_duplicate: true,
                    integration: {
                        name: "name",
                        categories: ["hris"],
                        color: "color",
                        slug: "slug",
                        passthrough_available: true,
                        available_model_operations: [
                            {
                                model_name: "Candidate",
                                available_operations: ["FETCH", "CREATE"],
                                required_post_parameters: ["remote_user_id"],
                                supported_fields: ["first_name", "last_name", "company", "title"],
                            },
                        ],
                    },
                    account_type: "PRODUCTION",
                    completed_at: "2024-08-26T20:11:19Z",
                },
            ],
        };
        server
            .mockEndpoint({ once: false })
            .get("/accounting/v1/linked-accounts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            next: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
            previous: "cj1sZXdwd2VycWVtY29zZnNkc2NzUWxNMEUxTXk0ME16UXpNallsTWtJ",
            results: [
                {
                    id: "e59b1821-f85c-4e28-a6b3-1804156f3563",
                    category: "hris",
                    status: "COMPLETE",
                    statusDetail: "Invalid login credentials",
                    endUserOriginId: "3ac95cde-6c7f-4eef-afec-be710b42308d",
                    endUserOrganizationName: "Foo Bar, LLC",
                    endUserEmailAddress: "hradmin@foobar.dev",
                    subdomain: "foobar",
                    webhookListenerUrl: "https://api.merge.dev/api/integrations/webhook-listener/7fc3mee0UW8ecV4",
                    isDuplicate: true,
                    integration: {
                        name: "name",
                        categories: ["hris"],
                        color: "color",
                        slug: "slug",
                        passthroughAvailable: true,
                        availableModelOperations: [
                            {
                                modelName: "Candidate",
                                availableOperations: ["FETCH", "CREATE"],
                                requiredPostParameters: ["remote_user_id"],
                                supportedFields: ["first_name", "last_name", "company", "title"],
                            },
                        ],
                    },
                    accountType: "PRODUCTION",
                    completedAt: new Date("2024-08-26T20:11:19.000Z"),
                },
            ],
        };
        const page = await client.accounting.linkedAccounts.list({
            category: "accounting",
            cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
            endUserEmailAddress: "end_user_email_address",
            endUserOrganizationName: "end_user_organization_name",
            endUserOriginId: "end_user_origin_id",
            endUserOriginIds: "end_user_origin_ids",
            id: "id",
            ids: "ids",
            includeDuplicates: true,
            integrationName: "integration_name",
            isTestAccount: "is_test_account",
            pageSize: 1,
            status: "status",
        });

        expect(expected.results).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.results).toEqual(nextPage.data);
    });
});
