/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { MethodEnum } from "./MethodEnum";
import { MultipartFormFieldRequest } from "./MultipartFormFieldRequest";
import { RequestFormatEnum } from "./RequestFormatEnum";

export const DataPassthroughRequest: core.serialization.ObjectSchema<
    serializers.hris.DataPassthroughRequest.Raw,
    Merge.hris.DataPassthroughRequest
> = core.serialization.object({
    method: MethodEnum,
    path: core.serialization.string(),
    baseUrlOverride: core.serialization.property("base_url_override", core.serialization.string().optionalNullable()),
    data: core.serialization.string().optionalNullable(),
    multipartFormData: core.serialization.property(
        "multipart_form_data",
        core.serialization.list(MultipartFormFieldRequest).optionalNullable(),
    ),
    headers: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    requestFormat: core.serialization.property("request_format", RequestFormatEnum.optionalNullable()),
    normalizeResponse: core.serialization.property("normalize_response", core.serialization.boolean().optional()),
});

export declare namespace DataPassthroughRequest {
    export interface Raw {
        method: MethodEnum.Raw;
        path: string;
        base_url_override?: (string | null) | null;
        data?: (string | null) | null;
        multipart_form_data?: (MultipartFormFieldRequest.Raw[] | null) | null;
        headers?: (Record<string, unknown> | null) | null;
        request_format?: (RequestFormatEnum.Raw | null) | null;
        normalize_response?: boolean | null;
    }
}
