// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { PayGroup } from "./PayGroup";

export const EmployeePayGroup: core.serialization.Schema<
    serializers.hris.EmployeePayGroup.Raw,
    Merge.hris.EmployeePayGroup
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PayGroup]);

export declare namespace EmployeePayGroup {
    export type Raw = string | PayGroup.Raw;
}
