/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const EmployeeMaritalStatus: core.serialization.Schema<
    serializers.hris.EmployeeMaritalStatus.Raw,
    Merge.hris.EmployeeMaritalStatus
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("../../..")).hris.MaritalStatusEnum),
    core.serialization.string(),
]);

export declare namespace EmployeeMaritalStatus {
    type Raw = serializers.hris.MaritalStatusEnum.Raw | string;
}
