// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Location } from "./Location";

export const EmployeeRequestWorkLocation: core.serialization.Schema<
    serializers.hris.EmployeeRequestWorkLocation.Raw,
    Merge.hris.EmployeeRequestWorkLocation
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Location]);

export declare namespace EmployeeRequestWorkLocation {
    export type Raw = string | Location.Raw;
}
