// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";

export const EmployeeManager: core.serialization.Schema<
    serializers.hris.EmployeeManager.Raw,
    Merge.hris.EmployeeManager
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(() => serializers.hris.Employee),
]);

export declare namespace EmployeeManager {
    export type Raw = string | serializers.hris.Employee.Raw;
}
