/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { EthnicityEnum } from "./EthnicityEnum";

export const EmployeeEthnicity: core.serialization.Schema<
    serializers.hris.EmployeeEthnicity.Raw,
    Merge.hris.EmployeeEthnicity
> = core.serialization.undiscriminatedUnion([EthnicityEnum, core.serialization.string()]);

export declare namespace EmployeeEthnicity {
    type Raw = EthnicityEnum.Raw | string;
}
