// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const MaritalStatusEnum: core.serialization.Schema<
    serializers.hris.MaritalStatusEnum.Raw,
    Merge.hris.MaritalStatusEnum
> = core.serialization.enum_([
    "SINGLE",
    "MARRIED_FILING_JOINTLY",
    "MARRIED_FILING_SEPARATELY",
    "HEAD_OF_HOUSEHOLD",
    "QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD",
]);

export declare namespace MaritalStatusEnum {
    export type Raw =
        | "SINGLE"
        | "MARRIED_FILING_JOINTLY"
        | "MARRIED_FILING_SEPARATELY"
        | "HEAD_OF_HOUSEHOLD"
        | "QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD";
}
