/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { BankInfo } from "./BankInfo";

export const PaginatedBankInfoList: core.serialization.ObjectSchema<
    serializers.hris.PaginatedBankInfoList.Raw,
    Merge.hris.PaginatedBankInfoList
> = core.serialization.object({
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization.list(BankInfo).optional(),
});

export declare namespace PaginatedBankInfoList {
    interface Raw {
        next?: string | null;
        previous?: string | null;
        results?: BankInfo.Raw[] | null;
    }
}
