// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const PolicyTypeEnum: core.serialization.Schema<serializers.hris.PolicyTypeEnum.Raw, Merge.hris.PolicyTypeEnum> =
    core.serialization.enum_(["VACATION", "SICK", "PERSONAL", "JURY_DUTY", "VOLUNTEER", "BEREAVEMENT"]);

export declare namespace PolicyTypeEnum {
    export type Raw = "VACATION" | "SICK" | "PERSONAL" | "JURY_DUTY" | "VOLUNTEER" | "BEREAVEMENT";
}
