/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";

export const SelectiveSyncConfigurationsUsageEnum: core.serialization.Schema<
    serializers.hris.SelectiveSyncConfigurationsUsageEnum.Raw,
    Merge.hris.SelectiveSyncConfigurationsUsageEnum
> = core.serialization.enum_(["IN_NEXT_SYNC", "IN_LAST_SYNC"]);

export declare namespace SelectiveSyncConfigurationsUsageEnum {
    export type Raw = "IN_NEXT_SYNC" | "IN_LAST_SYNC";
}
