/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const TeamParentTeam: core.serialization.Schema<serializers.hris.TeamParentTeam.Raw, Merge.hris.TeamParentTeam> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.lazyObject(async () => (await import("../../..")).hris.Team),
    ]);

export declare namespace TeamParentTeam {
    type Raw = string | serializers.hris.Team.Raw;
}
