// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../index";

/**
 * @example
 *     {
 *         isDebugMode: true,
 *         runAsync: true,
 *         body: {
 *             model: {}
 *         }
 *     }
 */
export interface ItemsAsyncBulkCreateRequest {
    /** Whether to include debug fields (such as log file links) in the response. */
    isDebugMode?: boolean;
    /** Whether or not third-party updates should be run asynchronously. */
    runAsync?: boolean;
    body: Merge.accounting.ItemEndpointRequest;
}
