/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BankInfoListRequestOrderBy = "-remote_created_at" | "remote_created_at";

export const BankInfoListRequestOrderBy = {
    RemoteCreatedAtDescending: "-remote_created_at",
    RemoteCreatedAtAscending: "remote_created_at",
} as const;
