/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The bank account type
 *
 * - `SAVINGS` - SAVINGS
 * - `CHECKING` - CHECKING
 */
export type BankInfoAccountType = Merge.hris.AccountTypeEnum | string;
