/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * The dependent's gender.
 *
 * - `MALE` - MALE
 * - `FEMALE` - FEMALE
 * - `NON-BINARY` - NON-BINARY
 * - `OTHER` - OTHER
 * - `PREFER_NOT_TO_DISCLOSE` - PREFER_NOT_TO_DISCLOSE
 */
export type DependentGender = Merge.hris.GenderEnum | string;
