// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

/**
 * The employee whose payroll is being run.
 */
export type EmployeePayrollRunEmployee = string | Merge.hris.Employee;
