/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * The employee's home address.
 */
export type EmployeeRequestHomeLocation = string | Merge.hris.Location;
