/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

export interface AsyncPostTask {
    status: Merge.accounting.AsyncPostTaskStatusEnum;
    result: Merge.accounting.AsyncPostTaskResult;
}
