/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The type of the account.
 *
 * - `BANK` - BANK
 * - `CREDIT_CARD` - CREDIT_CARD
 */
export type BankFeedAccountRequestAccountType = Merge.accounting.BankFeedAccountAccountTypeEnum | string;
