/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `BANK` - BANK
 * * `CREDIT_CARD` - CREDIT_CARD
 */
export type BankFeedAccountAccountTypeEnum = "BANK" | "CREDIT_CARD";
export const BankFeedAccountAccountTypeEnum = {
    Bank: "BANK",
    CreditCard: "CREDIT_CARD",
} as const;
