// This file was auto-generated by Fern from our API Definition.

/**
 * * `CLASS` - CLASS
 * * `DEPARTMENT` - DEPARTMENT
 */
export const CategoryTypeEnum = {
    Class: "CLASS",
    Department: "DEPARTMENT",
} as const;
export type CategoryTypeEnum = (typeof CategoryTypeEnum)[keyof typeof CategoryTypeEnum];
