// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

/**
 * The company the contact belongs to.
 */
export type ContactRequestCompany = string | Merge.accounting.CompanyInfo;
