/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * Identifier for the employee who submitted or is associated with the expense report
 */
export type ExpenseReportLineEmployee = string | Merge.accounting.Employee;
