/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * # The ExpenseLine Object
 * ### Description
 * The `ExpenseLine` object is used to represent an expense's line items.
 *
 * ### Usage Example
 * Fetch from the `GET Expense` endpoint and view the expense's line items.
 */
export interface ExpenseLineRequest {
    /** The third-party API ID of the matching object. */
    remoteId?: string;
    /** The line's item. */
    item?: Merge.accounting.ExpenseLineRequestItem;
    /** The line's net amount. */
    netAmount?: number;
    trackingCategory?: Merge.accounting.ExpenseLineRequestTrackingCategory;
    trackingCategories?: (Merge.accounting.ExpenseLineRequestTrackingCategoriesItem | undefined)[];
    /** The company the line belongs to. */
    company?: string;
    /** The expense's payment account. */
    account?: Merge.accounting.ExpenseLineRequestAccount;
    /** The expense's contact. */
    contact?: Merge.accounting.ExpenseLineRequestContact;
    /** The description of the item that was purchased by the company. */
    description?: string;
    /** The expense line item's exchange rate. */
    exchangeRate?: string;
    integrationParams?: Record<string, unknown>;
    linkedAccountParams?: Record<string, unknown>;
}
