// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

/**
 * The default purchase tax rate for this item.
 */
export type ItemPurchaseTaxRate = string | Merge.accounting.TaxRate;
