// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

/**
 * # The ItemFulfillment Object
 * ### Description
 * The `ItemFulfillment` object represents the recorded shipment or delivery of some or all items on an associated sales order.
 *
 * ### Usage Example
 * Fetch from the `LIST ItemFulfillments` endpoint and view a company's item fulfillments.
 */
export interface ItemFulfillmentRequestRequest {
    /** The ID of the sales order that the item fulfillment originated from. */
    salesOrder?: Merge.accounting.ItemFulfillmentRequestRequestSalesOrder;
    /** The date the fulfillment was created. */
    fulfillmentDate?: Date;
    /** The customer associated with the item fulfillment. */
    customer?: Merge.accounting.ItemFulfillmentRequestRequestCustomer;
    /** The subsidiary associated with the fulfillment. */
    company?: Merge.accounting.ItemFulfillmentRequestRequestCompany;
    /**
     * The status of the item fulfillment.
     *
     * * `DRAFT` - DRAFT
     * * `IN_PROGRESS` - IN_PROGRESS
     * * `SHIPPED` - SHIPPED
     * * `CANCELLED` - CANCELLED
     */
    status?: Merge.accounting.ItemFulfillmentRequestRequestStatus;
    /** Comment attached to the fulfillment. */
    memo?: string;
    lines?: Merge.accounting.ItemFulfillmentRequestRequestLinesItem[];
    integrationParams?: Record<string, unknown>;
    linkedAccountParams?: Record<string, unknown>;
    remoteFields?: Merge.accounting.RemoteFieldRequest[];
}
