/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

export interface PaginatedItemFulfillmentList {
    next?: string | null;
    previous?: string | null;
    results?: Merge.accounting.ItemFulfillment[];
}
