/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

export interface PaginatedContactList {
    next?: string | null;
    previous?: string | null;
    results?: Merge.accounting.Contact[];
}
