/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The supplier, or customer involved in the project.
 */
export type ProjectContact = string | Merge.accounting.Contact;
