/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The tracking category’s type.
 *
 * * `CLASS` - CLASS
 * * `DEPARTMENT` - DEPARTMENT
 */
export type TrackingCategoryCategoryType = string | Merge.accounting.CategoryTypeEnum;
