/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The vendor that owes the gift or refund.
 */
export type VendorCreditVendor = string | Merge.accounting.Contact;
