/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

/**
 * The status of the article.
 *
 * * `DRAFT` - DRAFT
 * * `PUBLISHED` - PUBLISHED
 * * `ARCHIVED` - ARCHIVED
 * * `TRASH` - TRASH
 */
export type ArticleStatus = Merge.knowledgebase.Status3C6Enum | string;
