/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `RAW` - RAW
 * * `BASE64` - BASE64
 * * `GZIP_BASE64` - GZIP_BASE64
 */
export type EncodingEnum = "RAW" | "BASE64" | "GZIP_BASE64";
export const EncodingEnum = {
    Raw: "RAW",
    Base64: "BASE64",
    GzipBase64: "GZIP_BASE64",
} as const;
