// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";
import { CollectionAccessLevel } from "./CollectionAccessLevel";
import { CollectionPermissionsItem } from "./CollectionPermissionsItem";
import { CollectionTypeEnum } from "./CollectionTypeEnum";
import { RemoteData } from "./RemoteData";

export const Collection: core.serialization.ObjectSchema<
    serializers.ticketing.Collection.Raw,
    Merge.ticketing.Collection
> = core.serialization.object({
    id: core.serialization.string().optional(),
    remoteId: core.serialization.property("remote_id", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    modifiedAt: core.serialization.property("modified_at", core.serialization.date().optional()),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    accessLevel: core.serialization.property("access_level", CollectionAccessLevel.optional()),
    collectionType: core.serialization.property("collection_type", CollectionTypeEnum.optional()),
    parentCollection: core.serialization.property(
        "parent_collection",
        core.serialization.lazy(() => serializers.ticketing.CollectionParentCollection).optional(),
    ),
    permissions: core.serialization.list(CollectionPermissionsItem).optional(),
    collectionUrl: core.serialization.property("collection_url", core.serialization.string().optional()),
    remoteCreatedAt: core.serialization.property("remote_created_at", core.serialization.date().optional()),
    remoteUpdatedAt: core.serialization.property("remote_updated_at", core.serialization.date().optional()),
    remoteWasDeleted: core.serialization.property("remote_was_deleted", core.serialization.boolean().optional()),
    fieldMappings: core.serialization.property(
        "field_mappings",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    remoteData: core.serialization.property("remote_data", core.serialization.list(RemoteData).optional()),
});

export declare namespace Collection {
    export interface Raw {
        id?: string | null;
        remote_id?: string | null;
        created_at?: string | null;
        modified_at?: string | null;
        name?: string | null;
        description?: string | null;
        access_level?: CollectionAccessLevel.Raw | null;
        collection_type?: CollectionTypeEnum.Raw | null;
        parent_collection?: serializers.ticketing.CollectionParentCollection.Raw | null;
        permissions?: CollectionPermissionsItem.Raw[] | null;
        collection_url?: string | null;
        remote_created_at?: string | null;
        remote_updated_at?: string | null;
        remote_was_deleted?: boolean | null;
        field_mappings?: Record<string, unknown> | null;
        remote_data?: RemoteData.Raw[] | null;
    }
}
