/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";

export const FieldFormatEnum: core.serialization.Schema<
    serializers.ticketing.FieldFormatEnum.Raw,
    Merge.ticketing.FieldFormatEnum
> = core.serialization.enum_(["string", "number", "date", "datetime", "bool", "list"]);

export declare namespace FieldFormatEnum {
    type Raw = "string" | "number" | "date" | "datetime" | "bool" | "list";
}
