/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { PriorityEnum } from "./PriorityEnum";

export const PatchedTicketRequestPriority: core.serialization.Schema<
    serializers.ticketing.PatchedTicketRequestPriority.Raw,
    Merge.ticketing.PatchedTicketRequestPriority
> = core.serialization.undiscriminatedUnion([PriorityEnum, core.serialization.string()]);

export declare namespace PatchedTicketRequestPriority {
    type Raw = PriorityEnum.Raw | string;
}
