/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const TicketStatusEnum: core.serialization.Schema<
    serializers.ticketing.TicketStatusEnum.Raw,
    Merge.ticketing.TicketStatusEnum
> = core.serialization.enum_(["OPEN", "CLOSED", "IN_PROGRESS", "ON_HOLD"]);

export declare namespace TicketStatusEnum {
    type Raw = "OPEN" | "CLOSED" | "IN_PROGRESS" | "ON_HOLD";
}
