// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient";
import { normalizeClientOptions } from "../../../../../../BaseClient";
import * as core from "../../../../../../core";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers";
import * as environments from "../../../../../../environments";
import * as errors from "../../../../../../errors/index";
import * as serializers from "../../../../../../serialization/index";
import type * as Merge from "../../../../../index";

export declare namespace AccountsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AccountsClient {
    protected readonly _options: AccountsClient.Options;

    constructor(options: AccountsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Returns a list of `Account` objects.
     *
     * @param {Merge.accounting.AccountsListRequest} request
     * @param {AccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.accounting.accounts.list({
     *         accountType: "account_type",
     *         classification: "",
     *         companyId: "company_id",
     *         createdAfter: new Date("2024-01-15T09:30:00.000Z"),
     *         createdBefore: new Date("2024-01-15T09:30:00.000Z"),
     *         cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
     *         expand: "company",
     *         includeDeletedData: true,
     *         includeRemoteData: true,
     *         includeShellData: true,
     *         modifiedAfter: new Date("2024-01-15T09:30:00.000Z"),
     *         modifiedBefore: new Date("2024-01-15T09:30:00.000Z"),
     *         name: "name",
     *         pageSize: 1,
     *         remoteFields: "classification",
     *         remoteId: "remote_id",
     *         showEnumOrigins: "classification",
     *         status: ""
     *     })
     */
    public list(
        request: Merge.accounting.AccountsListRequest = {},
        requestOptions?: AccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.accounting.PaginatedAccountList> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Merge.accounting.AccountsListRequest = {},
        requestOptions?: AccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.accounting.PaginatedAccountList>> {
        const {
            accountType,
            classification,
            companyId,
            createdAfter,
            createdBefore,
            cursor,
            expand,
            includeDeletedData,
            includeRemoteData,
            includeShellData,
            modifiedAfter,
            modifiedBefore,
            name,
            pageSize,
            remoteFields,
            remoteId,
            showEnumOrigins,
            status,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (accountType != null) {
            _queryParams.account_type = accountType;
        }

        if (classification != null) {
            _queryParams.classification = serializers.accounting.AccountsListRequestClassification.jsonOrThrow(
                classification,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        if (companyId != null) {
            _queryParams.company_id = companyId;
        }

        if (createdAfter != null) {
            _queryParams.created_after = createdAfter.toISOString();
        }

        if (createdBefore != null) {
            _queryParams.created_before = createdBefore.toISOString();
        }

        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (expand != null) {
            _queryParams.expand = expand;
        }

        if (includeDeletedData != null) {
            _queryParams.include_deleted_data = includeDeletedData.toString();
        }

        if (includeRemoteData != null) {
            _queryParams.include_remote_data = includeRemoteData.toString();
        }

        if (includeShellData != null) {
            _queryParams.include_shell_data = includeShellData.toString();
        }

        if (modifiedAfter != null) {
            _queryParams.modified_after = modifiedAfter.toISOString();
        }

        if (modifiedBefore != null) {
            _queryParams.modified_before = modifiedBefore.toISOString();
        }

        if (name != null) {
            _queryParams.name = name;
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (remoteFields != null) {
            _queryParams.remote_fields = serializers.accounting.AccountsListRequestRemoteFields.jsonOrThrow(
                remoteFields,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        if (remoteId != null) {
            _queryParams.remote_id = remoteId;
        }

        if (showEnumOrigins != null) {
            _queryParams.show_enum_origins = serializers.accounting.AccountsListRequestShowEnumOrigins.jsonOrThrow(
                showEnumOrigins,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        if (status != null) {
            _queryParams.status = serializers.accounting.AccountsListRequestStatus.jsonOrThrow(status, {
                unrecognizedObjectKeys: "strip",
            });
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "accounting/v1/accounts",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.accounting.PaginatedAccountList.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /accounting/v1/accounts.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates an `Account` object with the given values.
     *
     * @param {Merge.accounting.AccountEndpointRequest} request
     * @param {AccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.accounting.accounts.create({
     *         isDebugMode: true,
     *         runAsync: true,
     *         model: {}
     *     })
     */
    public create(
        request: Merge.accounting.AccountEndpointRequest,
        requestOptions?: AccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.accounting.AccountResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Merge.accounting.AccountEndpointRequest,
        requestOptions?: AccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.accounting.AccountResponse>> {
        const { isDebugMode, runAsync, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (isDebugMode != null) {
            _queryParams.is_debug_mode = isDebugMode.toString();
        }

        if (runAsync != null) {
            _queryParams.run_async = runAsync.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "accounting/v1/accounts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.accounting.AccountEndpointRequest.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.accounting.AccountResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling POST /accounting/v1/accounts.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns an `Account` object with the given `id`.
     *
     * @param {string} id
     * @param {Merge.accounting.AccountsRetrieveRequest} request
     * @param {AccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.accounting.accounts.retrieve("id", {
     *         expand: "company",
     *         includeRemoteData: true,
     *         includeShellData: true,
     *         remoteFields: "classification",
     *         showEnumOrigins: "classification"
     *     })
     */
    public retrieve(
        id: string,
        request: Merge.accounting.AccountsRetrieveRequest = {},
        requestOptions?: AccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.accounting.Account> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(id, request, requestOptions));
    }

    private async __retrieve(
        id: string,
        request: Merge.accounting.AccountsRetrieveRequest = {},
        requestOptions?: AccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.accounting.Account>> {
        const { expand, includeRemoteData, includeShellData, remoteFields, showEnumOrigins } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (expand != null) {
            _queryParams.expand = expand;
        }

        if (includeRemoteData != null) {
            _queryParams.include_remote_data = includeRemoteData.toString();
        }

        if (includeShellData != null) {
            _queryParams.include_shell_data = includeShellData.toString();
        }

        if (remoteFields != null) {
            _queryParams.remote_fields = serializers.accounting.AccountsRetrieveRequestRemoteFields.jsonOrThrow(
                remoteFields,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        if (showEnumOrigins != null) {
            _queryParams.show_enum_origins = serializers.accounting.AccountsRetrieveRequestShowEnumOrigins.jsonOrThrow(
                showEnumOrigins,
                { unrecognizedObjectKeys: "strip" },
            );
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `accounting/v1/accounts/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.accounting.Account.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError("Timeout exceeded when calling GET /accounting/v1/accounts/{id}.");
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns metadata for `Account` POSTs.
     *
     * @param {AccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.accounting.accounts.metaPostRetrieve()
     */
    public metaPostRetrieve(
        requestOptions?: AccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Merge.accounting.MetaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__metaPostRetrieve(requestOptions));
    }

    private async __metaPostRetrieve(
        requestOptions?: AccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.accounting.MetaResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Account-Token": requestOptions?.accountToken ?? this._options?.accountToken,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                "accounting/v1/accounts/meta/post",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.accounting.MetaResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError(
                    "Timeout exceeded when calling GET /accounting/v1/accounts/meta/post.",
                );
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.apiKey)}`;
    }
}
