/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Merge from "../../../../../../api";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.ticketing.forceResync.syncStatusResyncCreate.Response.Raw,
    Merge.ticketing.SyncStatus[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../../../..")).ticketing.SyncStatus)
);

export declare namespace Response {
    type Raw = serializers.ticketing.SyncStatus.Raw[];
}
