/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const AccountingPeriodStatus: core.serialization.Schema<
    serializers.accounting.AccountingPeriodStatus.Raw,
    Merge.accounting.AccountingPeriodStatus
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("../../..")).accounting.AccountingPeriodStatusEnum),
    core.serialization.string(),
]);

export declare namespace AccountingPeriodStatus {
    type Raw = serializers.accounting.AccountingPeriodStatusEnum.Raw | string;
}
