/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { AccountStatusEnum } from "./AccountStatusEnum";

export const AccountStatus: core.serialization.Schema<
    serializers.accounting.AccountStatus.Raw,
    Merge.accounting.AccountStatus
> = core.serialization.undiscriminatedUnion([AccountStatusEnum, core.serialization.string()]);

export declare namespace AccountStatus {
    export type Raw = AccountStatusEnum.Raw | string;
}
