/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const AddressCountry: core.serialization.Schema<
    serializers.accounting.AddressCountry.Raw,
    Merge.accounting.AddressCountry
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("../../..")).accounting.CountryEnum),
    core.serialization.string(),
]);

export declare namespace AddressCountry {
    type Raw = serializers.accounting.CountryEnum.Raw | string;
}
