// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Contact } from "./Contact";

export const CreditNoteLineItemRequestContact: core.serialization.Schema<
    serializers.accounting.CreditNoteLineItemRequestContact.Raw,
    Merge.accounting.CreditNoteLineItemRequestContact
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Contact]);

export declare namespace CreditNoteLineItemRequestContact {
    export type Raw = string | Contact.Raw;
}
