/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { CreditNoteLineItemRequest } from "./CreditNoteLineItemRequest";

export const CreditNoteRequestLineItemsItem: core.serialization.Schema<
    serializers.accounting.CreditNoteRequestLineItemsItem.Raw,
    Merge.accounting.CreditNoteRequestLineItemsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), CreditNoteLineItemRequest]);

export declare namespace CreditNoteRequestLineItemsItem {
    export type Raw = string | CreditNoteLineItemRequest.Raw;
}
