/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { CompanyInfo } from "./CompanyInfo";

export const ExpenseRequestCompany: core.serialization.Schema<
    serializers.accounting.ExpenseRequestCompany.Raw,
    Merge.accounting.ExpenseRequestCompany
> = core.serialization.undiscriminatedUnion([core.serialization.string(), CompanyInfo]);

export declare namespace ExpenseRequestCompany {
    type Raw = string | CompanyInfo.Raw;
}
