/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { TrackingCategory } from "./TrackingCategory";

export const ExpenseLineTrackingCategoriesItem: core.serialization.Schema<
    serializers.accounting.ExpenseLineTrackingCategoriesItem.Raw,
    Merge.accounting.ExpenseLineTrackingCategoriesItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), TrackingCategory]);

export declare namespace ExpenseLineTrackingCategoriesItem {
    type Raw = string | TrackingCategory.Raw;
}
