// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AccountRequest } from "./AccountRequest";

export const ExpenseLineRequestAccount: core.serialization.Schema<
    serializers.accounting.ExpenseLineRequestAccount.Raw,
    Merge.accounting.ExpenseLineRequestAccount
> = core.serialization.undiscriminatedUnion([core.serialization.string(), AccountRequest]);

export declare namespace ExpenseLineRequestAccount {
    export type Raw = string | AccountRequest.Raw;
}
