// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Account } from "./Account";

export const ExpenseRequestAccount: core.serialization.Schema<
    serializers.accounting.ExpenseRequestAccount.Raw,
    Merge.accounting.ExpenseRequestAccount
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Account]);

export declare namespace ExpenseRequestAccount {
    export type Raw = string | Account.Raw;
}
