// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { TransactionCurrencyEnum } from "./TransactionCurrencyEnum";

export const GeneralLedgerTransactionLineBaseCurrency: core.serialization.Schema<
    serializers.accounting.GeneralLedgerTransactionLineBaseCurrency.Raw,
    Merge.accounting.GeneralLedgerTransactionLineBaseCurrency
> = core.serialization.undiscriminatedUnion([TransactionCurrencyEnum, core.serialization.string()]);

export declare namespace GeneralLedgerTransactionLineBaseCurrency {
    export type Raw = TransactionCurrencyEnum.Raw | string;
}
