/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const InvoiceLineItemRequestItem: core.serialization.Schema<
    serializers.accounting.InvoiceLineItemRequestItem.Raw,
    Merge.accounting.InvoiceLineItemRequestItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("../../..")).accounting.Item),
]);

export declare namespace InvoiceLineItemRequestItem {
    type Raw = string | serializers.accounting.Item.Raw;
}
