/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { TrackingCategory } from "./TrackingCategory";

export const InvoiceLineItemRequestTrackingCategoriesItem: core.serialization.Schema<
    serializers.accounting.InvoiceLineItemRequestTrackingCategoriesItem.Raw,
    Merge.accounting.InvoiceLineItemRequestTrackingCategoriesItem
> = core.serialization.undiscriminatedUnion([TrackingCategory, core.serialization.string()]);

export declare namespace InvoiceLineItemRequestTrackingCategoriesItem {
    export type Raw = TrackingCategory.Raw | string;
}
