// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ItemFulfillmentEndpointRequest } from "./ItemFulfillmentEndpointRequest";

export const ItemFulfillmentBatchItemRequest: core.serialization.ObjectSchema<
    serializers.accounting.ItemFulfillmentBatchItemRequest.Raw,
    Merge.accounting.ItemFulfillmentBatchItemRequest
> = core.serialization.object({
    itemId: core.serialization.property("item_id", core.serialization.string()),
    payload: ItemFulfillmentEndpointRequest,
});

export declare namespace ItemFulfillmentBatchItemRequest {
    export interface Raw {
        item_id: string;
        payload: ItemFulfillmentEndpointRequest.Raw;
    }
}
