// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ItemFulfillmentLine } from "./ItemFulfillmentLine";

export const ItemFulfillmentLinesItem: core.serialization.Schema<
    serializers.accounting.ItemFulfillmentLinesItem.Raw,
    Merge.accounting.ItemFulfillmentLinesItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), ItemFulfillmentLine]);

export declare namespace ItemFulfillmentLinesItem {
    export type Raw = string | ItemFulfillmentLine.Raw;
}
