// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const MethodTypeEnum: core.serialization.Schema<
    serializers.accounting.MethodTypeEnum.Raw,
    Merge.accounting.MethodTypeEnum
> = core.serialization.enum_(["CREDIT_CARD", "DEBIT_CARD", "ACH", "CASH", "CHECK"]);

export declare namespace MethodTypeEnum {
    export type Raw = "CREDIT_CARD" | "DEBIT_CARD" | "ACH" | "CASH" | "CHECK";
}
