/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { Item } from "./Item";

export const PaginatedItemList: core.serialization.ObjectSchema<
    serializers.accounting.PaginatedItemList.Raw,
    Merge.accounting.PaginatedItemList
> = core.serialization.object({
    next: core.serialization.string().optionalNullable(),
    previous: core.serialization.string().optionalNullable(),
    results: core.serialization.list(Item).optional(),
});

export declare namespace PaginatedItemList {
    export interface Raw {
        next?: (string | null) | null;
        previous?: (string | null) | null;
        results?: Item.Raw[] | null;
    }
}
