/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { AccountingAttachment } from "./AccountingAttachment";

export const PaginatedAccountingAttachmentList: core.serialization.ObjectSchema<
    serializers.accounting.PaginatedAccountingAttachmentList.Raw,
    Merge.accounting.PaginatedAccountingAttachmentList
> = core.serialization.object({
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization.list(AccountingAttachment).optional(),
});

export declare namespace PaginatedAccountingAttachmentList {
    interface Raw {
        next?: string | null;
        previous?: string | null;
        results?: AccountingAttachment.Raw[] | null;
    }
}
