// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Status7D1Enum } from "./Status7D1Enum";

export const PatchedContactRequestStatus: core.serialization.Schema<
    serializers.accounting.PatchedContactRequestStatus.Raw,
    Merge.accounting.PatchedContactRequestStatus
> = core.serialization.undiscriminatedUnion([Status7D1Enum, core.serialization.string()]);

export declare namespace PatchedContactRequestStatus {
    export type Raw = Status7D1Enum.Raw | string;
}
