// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { PaymentMethod } from "./PaymentMethod";

export const PaymentPaymentMethod: core.serialization.Schema<
    serializers.accounting.PaymentPaymentMethod.Raw,
    Merge.accounting.PaymentPaymentMethod
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PaymentMethod]);

export declare namespace PaymentPaymentMethod {
    export type Raw = string | PaymentMethod.Raw;
}
