/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const PaymentsRetrieveRequestExpand: core.serialization.Schema<
    serializers.accounting.PaymentsRetrieveRequestExpand.Raw,
    Merge.accounting.PaymentsRetrieveRequestExpand
> = core.serialization.enum_([
    "account",
    "account,accounting_period",
    "account,company",
    "account,company,accounting_period",
    "accounting_period",
    "company",
    "company,accounting_period",
    "contact",
    "contact,account",
    "contact,account,accounting_period",
    "contact,account,company",
    "contact,account,company,accounting_period",
    "contact,accounting_period",
    "contact,company",
    "contact,company,accounting_period",
    "tracking_categories",
    "tracking_categories,account",
    "tracking_categories,account,accounting_period",
    "tracking_categories,account,company",
    "tracking_categories,account,company,accounting_period",
    "tracking_categories,accounting_period",
    "tracking_categories,company",
    "tracking_categories,company,accounting_period",
    "tracking_categories,contact",
    "tracking_categories,contact,account",
    "tracking_categories,contact,account,accounting_period",
    "tracking_categories,contact,account,company",
    "tracking_categories,contact,account,company,accounting_period",
    "tracking_categories,contact,accounting_period",
    "tracking_categories,contact,company",
    "tracking_categories,contact,company,accounting_period",
]);

export declare namespace PaymentsRetrieveRequestExpand {
    type Raw =
        | "account"
        | "account,accounting_period"
        | "account,company"
        | "account,company,accounting_period"
        | "accounting_period"
        | "company"
        | "company,accounting_period"
        | "contact"
        | "contact,account"
        | "contact,account,accounting_period"
        | "contact,account,company"
        | "contact,account,company,accounting_period"
        | "contact,accounting_period"
        | "contact,company"
        | "contact,company,accounting_period"
        | "tracking_categories"
        | "tracking_categories,account"
        | "tracking_categories,account,accounting_period"
        | "tracking_categories,account,company"
        | "tracking_categories,account,company,accounting_period"
        | "tracking_categories,accounting_period"
        | "tracking_categories,company"
        | "tracking_categories,company,accounting_period"
        | "tracking_categories,contact"
        | "tracking_categories,contact,account"
        | "tracking_categories,contact,account,accounting_period"
        | "tracking_categories,contact,account,company"
        | "tracking_categories,contact,account,company,accounting_period"
        | "tracking_categories,contact,accounting_period"
        | "tracking_categories,contact,company"
        | "tracking_categories,contact,company,accounting_period";
}
