/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const PurchaseOrderLineItemRequestItem: core.serialization.Schema<
    serializers.accounting.PurchaseOrderLineItemRequestItem.Raw,
    Merge.accounting.PurchaseOrderLineItemRequestItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("../../..")).accounting.Item),
]);

export declare namespace PurchaseOrderLineItemRequestItem {
    type Raw = string | serializers.accounting.Item.Raw;
}
