/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const Status7D1Enum: core.serialization.Schema<
    serializers.accounting.Status7D1Enum.Raw,
    Merge.accounting.Status7D1Enum
> = core.serialization.enum_(["ACTIVE", "ARCHIVED"]);

export declare namespace Status7D1Enum {
    type Raw = "ACTIVE" | "ARCHIVED";
}
