// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { SelectiveSyncConfigurationsUsageEnum } from "./SelectiveSyncConfigurationsUsageEnum";
import { SyncStatusLastSyncResult } from "./SyncStatusLastSyncResult";
import { SyncStatusStatus } from "./SyncStatusStatus";

export const SyncStatus: core.serialization.ObjectSchema<
    serializers.accounting.SyncStatus.Raw,
    Merge.accounting.SyncStatus
> = core.serialization.object({
    modelName: core.serialization.property("model_name", core.serialization.string()),
    modelId: core.serialization.property("model_id", core.serialization.string()),
    lastSyncStart: core.serialization.property("last_sync_start", core.serialization.date().optional()),
    nextSyncStart: core.serialization.property("next_sync_start", core.serialization.date().optional()),
    lastSyncResult: core.serialization.property("last_sync_result", SyncStatusLastSyncResult.optional()),
    lastSyncFinished: core.serialization.property("last_sync_finished", core.serialization.date().optional()),
    status: SyncStatusStatus,
    isInitialSync: core.serialization.property("is_initial_sync", core.serialization.boolean()),
    selectiveSyncConfigurationsUsage: core.serialization.property(
        "selective_sync_configurations_usage",
        SelectiveSyncConfigurationsUsageEnum.optional(),
    ),
});

export declare namespace SyncStatus {
    export interface Raw {
        model_name: string;
        model_id: string;
        last_sync_start?: string | null;
        next_sync_start?: string | null;
        last_sync_result?: SyncStatusLastSyncResult.Raw | null;
        last_sync_finished?: string | null;
        status: SyncStatusStatus.Raw;
        is_initial_sync: boolean;
        selective_sync_configurations_usage?: SelectiveSyncConfigurationsUsageEnum.Raw | null;
    }
}
