/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { TaxComponent } from "./TaxComponent";

export const TaxRateTaxComponentsItem: core.serialization.Schema<
    serializers.accounting.TaxRateTaxComponentsItem.Raw,
    Merge.accounting.TaxRateTaxComponentsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), TaxComponent]);

export declare namespace TaxRateTaxComponentsItem {
    type Raw = string | TaxComponent.Raw;
}
