// This file was auto-generated by Fern from our API Definition.

import { MergeClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TimeOffBalancesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new MergeClient({ apiKey: "test", accountToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            next: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
            previous: "cj1sZXdwd2VycWVtY29zZnNkc2NzUWxNMEUxTXk0ME16UXpNallsTWtJ",
            results: [
                {
                    id: "91b2b905-e866-40c8-8be2-efe53827a0aa",
                    remote_id: "19202938",
                    created_at: "2021-09-15T00:00:00Z",
                    modified_at: "2021-10-16T00:00:00Z",
                    employee: "employee",
                    balance: 1.1,
                    used: 1.1,
                    policy_type: "VACATION",
                    remote_was_deleted: true,
                    field_mappings: {
                        organization_defined_targets: { custom_key: "custom_value" },
                        linked_account_defined_targets: { custom_key: "custom_value" },
                    },
                    remote_data: [{ path: "/leave", data: ["Varies by platform"] }],
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/hris/v1/time-off-balances")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hris.timeOffBalances.list({
            createdAfter: new Date("2024-01-15T09:30:00.000Z"),
            createdBefore: new Date("2024-01-15T09:30:00.000Z"),
            cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
            employeeId: "employee_id",
            expand: "employee",
            includeDeletedData: true,
            includeRemoteData: true,
            includeShellData: true,
            modifiedAfter: new Date("2024-01-15T09:30:00.000Z"),
            modifiedBefore: new Date("2024-01-15T09:30:00.000Z"),
            pageSize: 1,
            policyType: "BEREAVEMENT",
            remoteFields: "policy_type",
            remoteId: "remote_id",
            showEnumOrigins: "policy_type",
        });
        expect(response).toEqual({
            next: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
            previous: "cj1sZXdwd2VycWVtY29zZnNkc2NzUWxNMEUxTXk0ME16UXpNallsTWtJ",
            results: [
                {
                    id: "91b2b905-e866-40c8-8be2-efe53827a0aa",
                    remoteId: "19202938",
                    createdAt: new Date("2021-09-15T00:00:00.000Z"),
                    modifiedAt: new Date("2021-10-16T00:00:00.000Z"),
                    employee: "employee",
                    balance: 1.1,
                    used: 1.1,
                    policyType: "VACATION",
                    remoteWasDeleted: true,
                    fieldMappings: {
                        organization_defined_targets: {
                            custom_key: "custom_value",
                        },
                        linked_account_defined_targets: {
                            custom_key: "custom_value",
                        },
                    },
                    remoteData: [
                        {
                            path: "/leave",
                            data: ["Varies by platform"],
                        },
                    ],
                },
            ],
        });
    });

    test("retrieve", async () => {
        const server = mockServerPool.createServer();
        const client = new MergeClient({ apiKey: "test", accountToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "91b2b905-e866-40c8-8be2-efe53827a0aa",
            remote_id: "19202938",
            created_at: "2021-09-15T00:00:00Z",
            modified_at: "2021-10-16T00:00:00Z",
            employee: "employee",
            balance: 1.1,
            used: 1.1,
            policy_type: "VACATION",
            remote_was_deleted: true,
            field_mappings: {
                organization_defined_targets: { custom_key: "custom_value" },
                linked_account_defined_targets: { custom_key: "custom_value" },
            },
            remote_data: [{ path: "/leave", data: ["Varies by platform"] }],
        };
        server
            .mockEndpoint()
            .get("/hris/v1/time-off-balances/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.hris.timeOffBalances.retrieve("id", {
            expand: "employee",
            includeRemoteData: true,
            includeShellData: true,
            remoteFields: "policy_type",
            showEnumOrigins: "policy_type",
        });
        expect(response).toEqual({
            id: "91b2b905-e866-40c8-8be2-efe53827a0aa",
            remoteId: "19202938",
            createdAt: new Date("2021-09-15T00:00:00.000Z"),
            modifiedAt: new Date("2021-10-16T00:00:00.000Z"),
            employee: "employee",
            balance: 1.1,
            used: 1.1,
            policyType: "VACATION",
            remoteWasDeleted: true,
            fieldMappings: {
                organization_defined_targets: {
                    custom_key: "custom_value",
                },
                linked_account_defined_targets: {
                    custom_key: "custom_value",
                },
            },
            remoteData: [
                {
                    path: "/leave",
                    data: ["Varies by platform"],
                },
            ],
        });
    });
});
