// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const InvoicesListRequestExpandItem: core.serialization.Schema<
    serializers.accounting.InvoicesListRequestExpandItem.Raw,
    Merge.accounting.InvoicesListRequestExpandItem
> = core.serialization.enum_([
    "accounting_period",
    "applied_credit_notes",
    "applied_payments",
    "applied_vendor_credits",
    "company",
    "contact",
    "employee",
    "line_items",
    "payment_term",
    "payments",
    "purchase_orders",
    "tracking_categories",
]);

export declare namespace InvoicesListRequestExpandItem {
    export type Raw =
        | "accounting_period"
        | "applied_credit_notes"
        | "applied_payments"
        | "applied_vendor_credits"
        | "company"
        | "contact"
        | "employee"
        | "line_items"
        | "payment_term"
        | "payments"
        | "purchase_orders"
        | "tracking_categories";
}
