// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ExternalTargetFieldApi } from "./ExternalTargetFieldApi";

export const ExternalTargetFieldApiResponse: core.serialization.ObjectSchema<
    serializers.fileStorage.ExternalTargetFieldApiResponse.Raw,
    Merge.fileStorage.ExternalTargetFieldApiResponse
> = core.serialization.object({
    file: core.serialization.property("File", core.serialization.list(ExternalTargetFieldApi).optional()),
    folder: core.serialization.property("Folder", core.serialization.list(ExternalTargetFieldApi).optional()),
    drive: core.serialization.property("Drive", core.serialization.list(ExternalTargetFieldApi).optional()),
    group: core.serialization.property("Group", core.serialization.list(ExternalTargetFieldApi).optional()),
    user: core.serialization.property("User", core.serialization.list(ExternalTargetFieldApi).optional()),
});

export declare namespace ExternalTargetFieldApiResponse {
    export interface Raw {
        File?: ExternalTargetFieldApi.Raw[] | null;
        Folder?: ExternalTargetFieldApi.Raw[] | null;
        Drive?: ExternalTargetFieldApi.Raw[] | null;
        Group?: ExternalTargetFieldApi.Raw[] | null;
        User?: ExternalTargetFieldApi.Raw[] | null;
    }
}
