/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";

export const PaginatedFolderList: core.serialization.ObjectSchema<
    serializers.filestorage.PaginatedFolderList.Raw,
    Merge.filestorage.PaginatedFolderList
> = core.serialization.object({
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization.list(core.serialization.lazyObject(() => serializers.filestorage.Folder)).optional(),
});

export declare namespace PaginatedFolderList {
    export interface Raw {
        next?: string | null;
        previous?: string | null;
        results?: serializers.filestorage.Folder.Raw[] | null;
    }
}
