/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Merge from "../../../../../index";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers";
import * as serializers from "../../../../../../serialization/index";
import * as errors from "../../../../../../errors/index";

export declare namespace Associations {
    export interface Options {
        environment?: core.Supplier<environments.MergeEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<core.BearerToken>;
        /** Override the X-Account-Token header */
        accountToken?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Account-Token header */
        accountToken?: string | undefined;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Associations {
    protected readonly _options: Associations.Options;

    constructor(_options: Associations.Options) {
        this._options = _options;
    }

    /**
     * Returns a list of `Association` objects.{/* BEGIN_CRM_CUSTOMOBJECTCLASS_FETCH_SUPPORTED_FIELDS * /}<Footer><MergeSupportedFieldsByIntegrationWidget requestType="GET" data="H4sIAAAAAAAAE9VSXU/bUAz9K8iPVT5WSoeINE0l7WgrJWUlTEMIRc6Nm972Jje9Hy0L4r9PaRmDje1pL3u0fXxsH58HYGiokOobBMBUCQ6UMicBAYRWG1nOshUxEwrUGhzAmsdYEgQQkSroKJxHR4PLCTigbV1LZSj/xEnkeqxoAQH4ZQtzbcUXnHJ/qbj2mdySwoL85xZ3se8BBwSv1pQPGJO2Mn8jOQBdPCB/CduyNuBAjVqbpZK2WM5pY0n/iXNdyZ2gvCA3Q33YTFBJlUHh5mjQf8HkqgPVW7n2hpwEGcqHaHBIhpjhsnqaujSm1oHvL0nU3n4DL6etT5WPynAmSPv93tnx6VnffWLZT/+YFuJDt7PaZDI77aQFEynaTpSw+ziZ7OJVcRKHJ/dxc92Pm3UTr9bvOmmBnSiJ+rPkpjcbDrqzNwDp1fuvZ1/Oh+fTuMOaUS9e3ezihHWjhK2zZtKbXrDddPz5Pm5ujqPhdS9ORv3phezOwrmOwrmMBp4HDvDKUKGwPVNDcPvwMvFklrHNrmppXoMnJRb0QpTDR7Dmbm0zwZmnex6W2MgKd9pjsvRLyjn6Y5vpWppUbywq8lZ18UN0LqtnxSGAUTwexOFo+NoIgy1ygZkgCIyy9JtzIbgFtrd+Kvfeb3+6N2iq2ZJK3PsUMxJpLaxC8RxqXhVWoAIHqvZuBxSV0lDKc7hrg43livJLVFiSIdWOunt03hLsCgXphVSM/o1mlwLNQqryJ69XV/+3bneP3wEsexsFvAQAAA==" /></Footer>{/* END_CRM_CUSTOMOBJECTCLASS_FETCH_SUPPORTED_FIELDS * /}
     *
     * @param {string} customObjectClassId
     * @param {string} objectId
     * @param {Merge.crm.CustomObjectClassesCustomObjectsAssociationsListAssociationsRequest} request
     * @param {Associations.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.associations.customObjectClassesCustomObjectsAssociationsList("custom_object_class_id", "object_id", {
     *         cursor: "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw"
     *     })
     */
    public customObjectClassesCustomObjectsAssociationsList(
        customObjectClassId: string,
        objectId: string,
        request: Merge.crm.CustomObjectClassesCustomObjectsAssociationsListAssociationsRequest = {},
        requestOptions?: Associations.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.PaginatedAssociationList> {
        return core.HttpResponsePromise.fromPromise(
            this.__customObjectClassesCustomObjectsAssociationsList(
                customObjectClassId,
                objectId,
                request,
                requestOptions,
            ),
        );
    }

    private async __customObjectClassesCustomObjectsAssociationsList(
        customObjectClassId: string,
        objectId: string,
        request: Merge.crm.CustomObjectClassesCustomObjectsAssociationsListAssociationsRequest = {},
        requestOptions?: Associations.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.PaginatedAssociationList>> {
        const {
            associationTypeId,
            createdAfter,
            createdBefore,
            cursor,
            expand,
            includeDeletedData,
            includeRemoteData,
            includeShellData,
            modifiedAfter,
            modifiedBefore,
            pageSize,
            remoteId,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (associationTypeId != null) {
            _queryParams["association_type_id"] = associationTypeId;
        }

        if (createdAfter != null) {
            _queryParams["created_after"] = createdAfter.toISOString();
        }

        if (createdBefore != null) {
            _queryParams["created_before"] = createdBefore.toISOString();
        }

        if (cursor != null) {
            _queryParams["cursor"] = cursor;
        }

        if (expand != null) {
            _queryParams["expand"] = expand;
        }

        if (includeDeletedData != null) {
            _queryParams["include_deleted_data"] = includeDeletedData.toString();
        }

        if (includeRemoteData != null) {
            _queryParams["include_remote_data"] = includeRemoteData.toString();
        }

        if (includeShellData != null) {
            _queryParams["include_shell_data"] = includeShellData.toString();
        }

        if (modifiedAfter != null) {
            _queryParams["modified_after"] = modifiedAfter.toISOString();
        }

        if (modifiedBefore != null) {
            _queryParams["modified_before"] = modifiedBefore.toISOString();
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        if (remoteId !== undefined) {
            _queryParams["remote_id"] = remoteId;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `crm/v1/custom-object-classes/${encodeURIComponent(customObjectClassId)}/custom-objects/${encodeURIComponent(objectId)}/associations`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.PaginatedAssociationList.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError(
                    "Timeout exceeded when calling GET /crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects/{object_id}/associations.",
                );
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates an Association between `source_object_id` and `target_object_id` of type `association_type_id`.
     *
     * @param {string} sourceClassId
     * @param {string} sourceObjectId
     * @param {string} targetClassId
     * @param {string} targetObjectId
     * @param {string} associationTypeId
     * @param {Merge.crm.CustomObjectClassesCustomObjectsAssociationsUpdateAssociationsRequest} request
     * @param {Associations.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.crm.associations.customObjectClassesCustomObjectsAssociationsUpdate("source_class_id", "source_object_id", "target_class_id", "target_object_id", "association_type_id")
     */
    public customObjectClassesCustomObjectsAssociationsUpdate(
        sourceClassId: string,
        sourceObjectId: string,
        targetClassId: string,
        targetObjectId: string,
        associationTypeId: string,
        request: Merge.crm.CustomObjectClassesCustomObjectsAssociationsUpdateAssociationsRequest = {},
        requestOptions?: Associations.RequestOptions,
    ): core.HttpResponsePromise<Merge.crm.Association> {
        return core.HttpResponsePromise.fromPromise(
            this.__customObjectClassesCustomObjectsAssociationsUpdate(
                sourceClassId,
                sourceObjectId,
                targetClassId,
                targetObjectId,
                associationTypeId,
                request,
                requestOptions,
            ),
        );
    }

    private async __customObjectClassesCustomObjectsAssociationsUpdate(
        sourceClassId: string,
        sourceObjectId: string,
        targetClassId: string,
        targetObjectId: string,
        associationTypeId: string,
        request: Merge.crm.CustomObjectClassesCustomObjectsAssociationsUpdateAssociationsRequest = {},
        requestOptions?: Associations.RequestOptions,
    ): Promise<core.WithRawResponse<Merge.crm.Association>> {
        const { isDebugMode, runAsync } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (isDebugMode != null) {
            _queryParams["is_debug_mode"] = isDebugMode.toString();
        }

        if (runAsync != null) {
            _queryParams["run_async"] = runAsync.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MergeEnvironment.Production,
                `crm/v1/custom-object-classes/${encodeURIComponent(sourceClassId)}/custom-objects/${encodeURIComponent(sourceObjectId)}/associations/${encodeURIComponent(targetClassId)}/${encodeURIComponent(targetObjectId)}/${encodeURIComponent(associationTypeId)}`,
            ),
            method: "PUT",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Account-Token": requestOptions?.accountToken,
                }),
                requestOptions?.headers,
            ),
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.crm.Association.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MergeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MergeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MergeTimeoutError(
                    "Timeout exceeded when calling PUT /crm/v1/custom-object-classes/{source_class_id}/custom-objects/{source_object_id}/associations/{target_class_id}/{target_object_id}/{association_type_id}.",
                );
            case "unknown":
                throw new errors.MergeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.apiKey)}`;
    }
}
