/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListAccountsRequestStatus = "" | "ACTIVE" | "INACTIVE" | "PENDING";
export const ListAccountsRequestStatus = {
    Empty: "",
    Active: "ACTIVE",
    Inactive: "INACTIVE",
    Pending: "PENDING",
} as const;
