/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

export interface CommentResponse {
    model: Merge.ticketing.Comment;
    warnings: Merge.ticketing.WarningValidationProblem[];
    errors: Merge.ticketing.ErrorValidationProblem[];
    logs?: Merge.ticketing.DebugModeLog[];
}
