// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../index";

export interface MetaResponse {
    requestSchema: Record<string, unknown>;
    remoteFieldClasses?: Record<string, unknown>;
    status?: Merge.ticketing.LinkedAccountStatus;
    hasConditionalParams: boolean;
    hasRequiredLinkedAccountParams: boolean;
}
