/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../../index";

export interface RemoteFieldRequest {
    remoteFieldClass: Merge.ticketing.RemoteFieldRequestRemoteFieldClass;
    value?: unknown;
}
