/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Merge from "../../..";

/**
 * # The Team Object
 *
 * ### Description
 *
 * The `Team` object is used to represent a team within the company receiving the ticket.
 *
 * ### Usage Example
 *
 * TODO
 */
export interface Team {
    id?: string;
    /** The third-party API ID of the matching object. */
    remoteId?: string;
    createdAt?: Date;
    /** This is the datetime that this object was last updated by Merge */
    modifiedAt?: Date;
    /** The team's name. */
    name?: string;
    /** The team's description. */
    description?: string;
    /** Indicates whether or not this object has been deleted in the third party platform. */
    remoteWasDeleted?: boolean;
    fieldMappings?: Record<string, unknown>;
    remoteData?: Merge.ticketing.RemoteData[];
}
