/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TicketsCollaboratorsListRequestExpand = "roles" | "teams" | "teams,roles";

export const TicketsCollaboratorsListRequestExpand = {
    Roles: "roles",
    Teams: "teams",
    TeamsRoles: "teams,roles",
} as const;
