/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `ALL` - ALL
 * * `ASSIGNED_ONLY` - ASSIGNED_ONLY
 * * `TEAM_ONLY` - TEAM_ONLY
 */
export type TicketAccessEnum = "ALL" | "ASSIGNED_ONLY" | "TEAM_ONLY";

export const TicketAccessEnum = {
    All: "ALL",
    AssignedOnly: "ASSIGNED_ONLY",
    TeamOnly: "TEAM_ONLY",
} as const;
