/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * * `COMPANY` - COMPANY
 * * `PUBLIC` - PUBLIC
 * * `PRIVATE` - PRIVATE
 * * `COLLECTION` - COLLECTION
 */
export type TicketAccessLevelEnum = "COMPANY" | "PUBLIC" | "PRIVATE" | "COLLECTION";
export const TicketAccessLevelEnum = {
    Company: "COMPANY",
    Public: "PUBLIC",
    Private: "PRIVATE",
    Collection: "COLLECTION",
} as const;
