// This file was auto-generated by Fern from our API Definition.

export const CommentsRetrieveRequestExpand = {
    Contact: "contact",
    ContactTicket: "contact,ticket",
    Ticket: "ticket",
    User: "user",
    UserContact: "user,contact",
    UserContactTicket: "user,contact,ticket",
    UserTicket: "user,ticket",
} as const;
export type CommentsRetrieveRequestExpand =
    (typeof CommentsRetrieveRequestExpand)[keyof typeof CommentsRetrieveRequestExpand];
