// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";
import { ItemBatchItem } from "../../../../types/ItemBatchItem";

export const ItemBulkRequest: core.serialization.Schema<
    serializers.accounting.ItemBulkRequest.Raw,
    Omit<Merge.accounting.ItemBulkRequest, "isDebugMode" | "runAsync">
> = core.serialization.object({
    batchItems: core.serialization.property("batch_items", core.serialization.list(ItemBatchItem)),
});

export declare namespace ItemBulkRequest {
    export interface Raw {
        batch_items: ItemBatchItem.Raw[];
    }
}
