// This file was auto-generated by Fern from our API Definition.

export const PaymentsRetrieveRequestExpandItem = {
    Account: "account",
    AccountingPeriod: "accounting_period",
    AppliedToLines: "applied_to_lines",
    Company: "company",
    Contact: "contact",
    PaymentMethod: "payment_method",
    TrackingCategories: "tracking_categories",
} as const;
export type PaymentsRetrieveRequestExpandItem =
    (typeof PaymentsRetrieveRequestExpandItem)[keyof typeof PaymentsRetrieveRequestExpandItem];
