/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RetrieveCreditNotesRequestRemoteFields = "status" | "status,type" | "type";
export const RetrieveCreditNotesRequestRemoteFields = {
    Status: "status",
    StatusType: "status,type",
    Type: "type",
} as const;
