// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { RemoteResponse } from "../../../types/RemoteResponse";

export const AsyncPassthroughRetrieveResponse: core.serialization.Schema<
    serializers.crm.AsyncPassthroughRetrieveResponse.Raw,
    Merge.crm.AsyncPassthroughRetrieveResponse
> = core.serialization.undiscriminatedUnion([RemoteResponse, core.serialization.string()]);

export declare namespace AsyncPassthroughRetrieveResponse {
    export type Raw = RemoteResponse.Raw | string;
}
