/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Merge from "../../../../api";
import * as core from "../../../../core";

export const ApplicationOffersItem: core.serialization.Schema<
    serializers.ats.ApplicationOffersItem.Raw,
    Merge.ats.ApplicationOffersItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("../../..")).ats.Offer),
]);

export declare namespace ApplicationOffersItem {
    type Raw = string | serializers.ats.Offer.Raw;
}
