/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import { JobInterviewStage } from "./JobInterviewStage";

export const ApplicationCurrentStage: core.serialization.Schema<
    serializers.ats.ApplicationCurrentStage.Raw,
    Merge.ats.ApplicationCurrentStage
> = core.serialization.undiscriminatedUnion([core.serialization.string(), JobInterviewStage]);

export declare namespace ApplicationCurrentStage {
    type Raw = string | JobInterviewStage.Raw;
}
