// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";
import { DebugModeLog } from "./DebugModeLog";
import { ErrorValidationProblem } from "./ErrorValidationProblem";
import { WarningValidationProblem } from "./WarningValidationProblem";

export const CandidateResponse: core.serialization.ObjectSchema<
    serializers.ats.CandidateResponse.Raw,
    Merge.ats.CandidateResponse
> = core.serialization.object({
    model: core.serialization.lazyObject(() => serializers.ats.Candidate),
    warnings: core.serialization.list(WarningValidationProblem),
    errors: core.serialization.list(ErrorValidationProblem),
    logs: core.serialization.list(DebugModeLog).optional(),
});

export declare namespace CandidateResponse {
    export interface Raw {
        model: serializers.ats.Candidate.Raw;
        warnings: WarningValidationProblem.Raw[];
        errors: ErrorValidationProblem.Raw[];
        logs?: DebugModeLog.Raw[] | null;
    }
}
