// This file was auto-generated by Fern from our API Definition.

import type * as Merge from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const VisibilityEnum: core.serialization.Schema<serializers.ats.VisibilityEnum.Raw, Merge.ats.VisibilityEnum> =
    core.serialization.enum_(["ADMIN_ONLY", "PUBLIC", "PRIVATE"]);

export declare namespace VisibilityEnum {
    export type Raw = "ADMIN_ONLY" | "PUBLIC" | "PRIVATE";
}
